# GENERATED by tests/gen_bson_vectors.py — do not edit by hand.
# Regenerate: python3 tests/gen_bson_vectors.py && pixi run format
# BSON vectors: decodes compare dumps text, encodes compare exact
# bytes, every accept round-trips encode→decode, rejects must raise.

from bson import decode
from bson import dumps as bson_dumps
from json import dumps, loads


def _unhex(hex: String) raises -> List[UInt8]:
    var out = List[UInt8](capacity=hex.byte_length() // 2)
    var chars = hex.as_bytes()
    var i = 0
    while i + 1 < len(chars):
        out.append(UInt8((_nib(chars[i]) << 4) | _nib(chars[i + 1])))
        i += 2
    return out^


def _nib(c: UInt8) raises -> Int:
    if c >= UInt8(ord("0")) and c <= UInt8(ord("9")):
        return Int(c - UInt8(ord("0")))
    return Int(c - UInt8(ord("a"))) + 10


def _to_hex(data: List[UInt8]) -> String:
    comptime HEX = "0123456789abcdef"
    var hb = HEX.as_bytes()
    var out = String("")
    for i in range(len(data)):
        out += chr(Int(hb[Int((data[i] >> 4) & 15)]))
        out += chr(Int(hb[Int(data[i] & 15)]))
    return out^


def main() raises:
    var fails = 0
    var accepts = 0
    var rejects = 0
    var encodes = 0
    var roundtrips = 0

    try:
        var d = decode(_unhex("0500000000"))
        if dumps(d) == "{}":
            accepts += 1
        else:
            print("FAIL accept:", "0500000000", "got", dumps(d))
            fails += 1
    except error:
        print("FAIL accept raised:", "0500000000", String(error))
        fails += 1
    try:
        var d = decode(_unhex("0c0000001061000100000000"))
        if dumps(d) == '{"a":1}':
            accepts += 1
        else:
            print("FAIL accept:", "0c0000001061000100000000", "got", dumps(d))
            fails += 1
    except error:
        print("FAIL accept raised:", "0c0000001061000100000000", String(error))
        fails += 1
    try:
        var d = decode(_unhex("0c000000106e00d4feffff00"))
        if dumps(d) == '{"n":-300}':
            accepts += 1
        else:
            print("FAIL accept:", "0c000000106e00d4feffff00", "got", dumps(d))
            fails += 1
    except error:
        print("FAIL accept raised:", "0c000000106e00d4feffff00", String(error))
        fails += 1
    try:
        var d = decode(_unhex("120000001262696700000000000100000000"))
        if dumps(d) == '{"big":4294967296}':
            accepts += 1
        else:
            print(
                "FAIL accept:",
                "120000001262696700000000000100000000",
                "got",
                dumps(d),
            )
            fails += 1
    except error:
        print(
            "FAIL accept raised:",
            "120000001262696700000000000100000000",
            String(error),
        )
        fails += 1
    try:
        var d = decode(_unhex("12000000126d696e00000000000000008000"))
        if dumps(d) == '{"min":-9223372036854775808}':
            accepts += 1
        else:
            print(
                "FAIL accept:",
                "12000000126d696e00000000000000008000",
                "got",
                dumps(d),
            )
            fails += 1
    except error:
        print(
            "FAIL accept raised:",
            "12000000126d696e00000000000000008000",
            String(error),
        )
        fails += 1
    try:
        var d = decode(_unhex("10000000016600000000000000f83f00"))
        if dumps(d) == '{"f":1.5}':
            accepts += 1
        else:
            print(
                "FAIL accept:",
                "10000000016600000000000000f83f00",
                "got",
                dumps(d),
            )
            fails += 1
    except error:
        print(
            "FAIL accept raised:",
            "10000000016600000000000000f83f00",
            String(error),
        )
        fails += 1
    try:
        var d = decode(_unhex("0f0000000273000300000068690000"))
        if dumps(d) == '{"s":"hi"}':
            accepts += 1
        else:
            print(
                "FAIL accept:",
                "0f0000000273000300000068690000",
                "got",
                dumps(d),
            )
            fails += 1
    except error:
        print(
            "FAIL accept raised:",
            "0f0000000273000300000068690000",
            String(error),
        )
        fails += 1
    try:
        var d = decode(_unhex("130000000275000700000068c3a96c6c6f0000"))
        if dumps(d) == '{"u":"héllo"}':
            accepts += 1
        else:
            print(
                "FAIL accept:",
                "130000000275000700000068c3a96c6c6f0000",
                "got",
                dumps(d),
            )
            fails += 1
    except error:
        print(
            "FAIL accept raised:",
            "130000000275000700000068c3a96c6c6f0000",
            String(error),
        )
        fails += 1
    try:
        var d = decode(_unhex("11000000026400050000006122620a0000"))
        if dumps(d) == '{"d":"a\\"b\\n"}':
            accepts += 1
        else:
            print(
                "FAIL accept:",
                "11000000026400050000006122620a0000",
                "got",
                dumps(d),
            )
            fails += 1
    except error:
        print(
            "FAIL accept raised:",
            "11000000026400050000006122620a0000",
            String(error),
        )
        fails += 1
    try:
        var d = decode(_unhex("0d000000087400010866000000"))
        if dumps(d) == '{"t":true,"f":false}':
            accepts += 1
        else:
            print("FAIL accept:", "0d000000087400010866000000", "got", dumps(d))
            fails += 1
    except error:
        print(
            "FAIL accept raised:", "0d000000087400010866000000", String(error)
        )
        fails += 1
    try:
        var d = decode(_unhex("080000000a7a0000"))
        if dumps(d) == '{"z":null}':
            accepts += 1
        else:
            print("FAIL accept:", "080000000a7a0000", "got", dumps(d))
            fails += 1
    except error:
        print("FAIL accept raised:", "080000000a7a0000", String(error))
        fails += 1
    try:
        var d = decode(
            _unhex("1b0000000461001300000010300001000000103100020000000000")
        )
        if dumps(d) == '{"a":[1,2]}':
            accepts += 1
        else:
            print(
                "FAIL accept:",
                "1b0000000461001300000010300001000000103100020000000000",
                "got",
                dumps(d),
            )
            fails += 1
    except error:
        print(
            "FAIL accept raised:",
            "1b0000000461001300000010300001000000103100020000000000",
            String(error),
        )
        fails += 1
    try:
        var d = decode(_unhex("16000000036f000e000000026b000200000076000000"))
        if dumps(d) == '{"o":{"k":"v"}}':
            accepts += 1
        else:
            print(
                "FAIL accept:",
                "16000000036f000e000000026b000200000076000000",
                "got",
                dumps(d),
            )
            fails += 1
    except error:
        print(
            "FAIL accept raised:",
            "16000000036f000e000000026b000200000076000000",
            String(error),
        )
        fails += 1
    try:
        var d = decode(
            _unhex("18000000046e657374000d00000004300005000000000000")
        )
        if dumps(d) == '{"nest":[[]]}':
            accepts += 1
        else:
            print(
                "FAIL accept:",
                "18000000046e657374000d00000004300005000000000000",
                "got",
                dumps(d),
            )
            fails += 1
    except error:
        print(
            "FAIL accept raised:",
            "18000000046e657374000d00000004300005000000000000",
            String(error),
        )
        fails += 1
    try:
        var d = decode(_unhex("1500000002000a000000656d7074792d6b65790000"))
        if dumps(d) == '{"":"empty-key"}':
            accepts += 1
        else:
            print(
                "FAIL accept:",
                "1500000002000a000000656d7074792d6b65790000",
                "got",
                dumps(d),
            )
            fails += 1
    except error:
        print(
            "FAIL accept raised:",
            "1500000002000a000000656d7074792d6b65790000",
            String(error),
        )
        fails += 1

    try:
        var e = bson_dumps(loads(String("{}")))
        if _to_hex(e) == "0500000000":
            encodes += 1
        else:
            print("FAIL encode:", "{}", "got", _to_hex(e))
            fails += 1
    except error:
        print("FAIL encode raised:", "{}", String(error))
        fails += 1
    try:
        var e = bson_dumps(loads(String('{"a":1}')))
        if _to_hex(e) == "0c0000001061000100000000":
            encodes += 1
        else:
            print("FAIL encode:", '{"a":1}', "got", _to_hex(e))
            fails += 1
    except error:
        print("FAIL encode raised:", '{"a":1}', String(error))
        fails += 1
    try:
        var e = bson_dumps(loads(String('{"big":4294967296}')))
        if _to_hex(e) == "120000001262696700000000000100000000":
            encodes += 1
        else:
            print("FAIL encode:", '{"big":4294967296}', "got", _to_hex(e))
            fails += 1
    except error:
        print("FAIL encode raised:", '{"big":4294967296}', String(error))
        fails += 1
    try:
        var e = bson_dumps(loads(String('{"f":1.5}')))
        if _to_hex(e) == "10000000016600000000000000f83f00":
            encodes += 1
        else:
            print("FAIL encode:", '{"f":1.5}', "got", _to_hex(e))
            fails += 1
    except error:
        print("FAIL encode raised:", '{"f":1.5}', String(error))
        fails += 1
    try:
        var e = bson_dumps(loads(String('{"s":"hi"}')))
        if _to_hex(e) == "0f0000000273000300000068690000":
            encodes += 1
        else:
            print("FAIL encode:", '{"s":"hi"}', "got", _to_hex(e))
            fails += 1
    except error:
        print("FAIL encode raised:", '{"s":"hi"}', String(error))
        fails += 1
    try:
        var e = bson_dumps(loads(String('{"z":null,"t":true}')))
        if _to_hex(e) == "0c0000000a7a000874000100":
            encodes += 1
        else:
            print("FAIL encode:", '{"z":null,"t":true}', "got", _to_hex(e))
            fails += 1
    except error:
        print("FAIL encode raised:", '{"z":null,"t":true}', String(error))
        fails += 1
    try:
        var e = bson_dumps(loads(String('{"a":[1,2]}')))
        if (
            _to_hex(e)
            == "1b0000000461001300000010300001000000103100020000000000"
        ):
            encodes += 1
        else:
            print("FAIL encode:", '{"a":[1,2]}', "got", _to_hex(e))
            fails += 1
    except error:
        print("FAIL encode raised:", '{"a":[1,2]}', String(error))
        fails += 1
    try:
        var e = bson_dumps(loads(String('{"o":{"k":"v"}}')))
        if _to_hex(e) == "16000000036f000e000000026b000200000076000000":
            encodes += 1
        else:
            print("FAIL encode:", '{"o":{"k":"v"}}', "got", _to_hex(e))
            fails += 1
    except error:
        print("FAIL encode raised:", '{"o":{"k":"v"}}', String(error))
        fails += 1
    try:
        var e = bson_dumps(loads(String('{"neg":-2147483648}')))
        if _to_hex(e) == "0e000000106e6567000000008000":
            encodes += 1
        else:
            print("FAIL encode:", '{"neg":-2147483648}', "got", _to_hex(e))
            fails += 1
    except error:
        print("FAIL encode raised:", '{"neg":-2147483648}', String(error))
        fails += 1
    try:
        var e = bson_dumps(loads(String('{"past":-2147483649}')))
        if _to_hex(e) == "13000000127061737400ffffff7fffffffff00":
            encodes += 1
        else:
            print("FAIL encode:", '{"past":-2147483649}', "got", _to_hex(e))
            fails += 1
    except error:
        print("FAIL encode raised:", '{"past":-2147483649}', String(error))
        fails += 1

    try:
        var r1 = decode(_unhex("0500000000"))
        var r2 = decode(bson_dumps(r1))
        if dumps(r2) == "{}":
            roundtrips += 1
        else:
            print("FAIL roundtrip:", "0500000000", "got", dumps(r2))
            fails += 1
    except error:
        print("FAIL roundtrip raised:", "0500000000", String(error))
        fails += 1
    try:
        var r1 = decode(_unhex("0c0000001061000100000000"))
        var r2 = decode(bson_dumps(r1))
        if dumps(r2) == '{"a":1}':
            roundtrips += 1
        else:
            print(
                "FAIL roundtrip:", "0c0000001061000100000000", "got", dumps(r2)
            )
            fails += 1
    except error:
        print(
            "FAIL roundtrip raised:", "0c0000001061000100000000", String(error)
        )
        fails += 1
    try:
        var r1 = decode(_unhex("0c000000106e00d4feffff00"))
        var r2 = decode(bson_dumps(r1))
        if dumps(r2) == '{"n":-300}':
            roundtrips += 1
        else:
            print(
                "FAIL roundtrip:", "0c000000106e00d4feffff00", "got", dumps(r2)
            )
            fails += 1
    except error:
        print(
            "FAIL roundtrip raised:", "0c000000106e00d4feffff00", String(error)
        )
        fails += 1
    try:
        var r1 = decode(_unhex("120000001262696700000000000100000000"))
        var r2 = decode(bson_dumps(r1))
        if dumps(r2) == '{"big":4294967296}':
            roundtrips += 1
        else:
            print(
                "FAIL roundtrip:",
                "120000001262696700000000000100000000",
                "got",
                dumps(r2),
            )
            fails += 1
    except error:
        print(
            "FAIL roundtrip raised:",
            "120000001262696700000000000100000000",
            String(error),
        )
        fails += 1
    try:
        var r1 = decode(_unhex("12000000126d696e00000000000000008000"))
        var r2 = decode(bson_dumps(r1))
        if dumps(r2) == '{"min":-9223372036854775808}':
            roundtrips += 1
        else:
            print(
                "FAIL roundtrip:",
                "12000000126d696e00000000000000008000",
                "got",
                dumps(r2),
            )
            fails += 1
    except error:
        print(
            "FAIL roundtrip raised:",
            "12000000126d696e00000000000000008000",
            String(error),
        )
        fails += 1
    try:
        var r1 = decode(_unhex("10000000016600000000000000f83f00"))
        var r2 = decode(bson_dumps(r1))
        if dumps(r2) == '{"f":1.5}':
            roundtrips += 1
        else:
            print(
                "FAIL roundtrip:",
                "10000000016600000000000000f83f00",
                "got",
                dumps(r2),
            )
            fails += 1
    except error:
        print(
            "FAIL roundtrip raised:",
            "10000000016600000000000000f83f00",
            String(error),
        )
        fails += 1
    try:
        var r1 = decode(_unhex("0f0000000273000300000068690000"))
        var r2 = decode(bson_dumps(r1))
        if dumps(r2) == '{"s":"hi"}':
            roundtrips += 1
        else:
            print(
                "FAIL roundtrip:",
                "0f0000000273000300000068690000",
                "got",
                dumps(r2),
            )
            fails += 1
    except error:
        print(
            "FAIL roundtrip raised:",
            "0f0000000273000300000068690000",
            String(error),
        )
        fails += 1
    try:
        var r1 = decode(_unhex("130000000275000700000068c3a96c6c6f0000"))
        var r2 = decode(bson_dumps(r1))
        if dumps(r2) == '{"u":"héllo"}':
            roundtrips += 1
        else:
            print(
                "FAIL roundtrip:",
                "130000000275000700000068c3a96c6c6f0000",
                "got",
                dumps(r2),
            )
            fails += 1
    except error:
        print(
            "FAIL roundtrip raised:",
            "130000000275000700000068c3a96c6c6f0000",
            String(error),
        )
        fails += 1
    try:
        var r1 = decode(_unhex("11000000026400050000006122620a0000"))
        var r2 = decode(bson_dumps(r1))
        if dumps(r2) == '{"d":"a\\"b\\n"}':
            roundtrips += 1
        else:
            print(
                "FAIL roundtrip:",
                "11000000026400050000006122620a0000",
                "got",
                dumps(r2),
            )
            fails += 1
    except error:
        print(
            "FAIL roundtrip raised:",
            "11000000026400050000006122620a0000",
            String(error),
        )
        fails += 1
    try:
        var r1 = decode(_unhex("0d000000087400010866000000"))
        var r2 = decode(bson_dumps(r1))
        if dumps(r2) == '{"t":true,"f":false}':
            roundtrips += 1
        else:
            print(
                "FAIL roundtrip:",
                "0d000000087400010866000000",
                "got",
                dumps(r2),
            )
            fails += 1
    except error:
        print(
            "FAIL roundtrip raised:",
            "0d000000087400010866000000",
            String(error),
        )
        fails += 1
    try:
        var r1 = decode(_unhex("080000000a7a0000"))
        var r2 = decode(bson_dumps(r1))
        if dumps(r2) == '{"z":null}':
            roundtrips += 1
        else:
            print("FAIL roundtrip:", "080000000a7a0000", "got", dumps(r2))
            fails += 1
    except error:
        print("FAIL roundtrip raised:", "080000000a7a0000", String(error))
        fails += 1
    try:
        var r1 = decode(
            _unhex("1b0000000461001300000010300001000000103100020000000000")
        )
        var r2 = decode(bson_dumps(r1))
        if dumps(r2) == '{"a":[1,2]}':
            roundtrips += 1
        else:
            print(
                "FAIL roundtrip:",
                "1b0000000461001300000010300001000000103100020000000000",
                "got",
                dumps(r2),
            )
            fails += 1
    except error:
        print(
            "FAIL roundtrip raised:",
            "1b0000000461001300000010300001000000103100020000000000",
            String(error),
        )
        fails += 1
    try:
        var r1 = decode(_unhex("16000000036f000e000000026b000200000076000000"))
        var r2 = decode(bson_dumps(r1))
        if dumps(r2) == '{"o":{"k":"v"}}':
            roundtrips += 1
        else:
            print(
                "FAIL roundtrip:",
                "16000000036f000e000000026b000200000076000000",
                "got",
                dumps(r2),
            )
            fails += 1
    except error:
        print(
            "FAIL roundtrip raised:",
            "16000000036f000e000000026b000200000076000000",
            String(error),
        )
        fails += 1
    try:
        var r1 = decode(
            _unhex("18000000046e657374000d00000004300005000000000000")
        )
        var r2 = decode(bson_dumps(r1))
        if dumps(r2) == '{"nest":[[]]}':
            roundtrips += 1
        else:
            print(
                "FAIL roundtrip:",
                "18000000046e657374000d00000004300005000000000000",
                "got",
                dumps(r2),
            )
            fails += 1
    except error:
        print(
            "FAIL roundtrip raised:",
            "18000000046e657374000d00000004300005000000000000",
            String(error),
        )
        fails += 1
    try:
        var r1 = decode(_unhex("1500000002000a000000656d7074792d6b65790000"))
        var r2 = decode(bson_dumps(r1))
        if dumps(r2) == '{"":"empty-key"}':
            roundtrips += 1
        else:
            print(
                "FAIL roundtrip:",
                "1500000002000a000000656d7074792d6b65790000",
                "got",
                dumps(r2),
            )
            fails += 1
    except error:
        print(
            "FAIL roundtrip raised:",
            "1500000002000a000000656d7074792d6b65790000",
            String(error),
        )
        fails += 1

    try:
        _ = decode(_unhex(""))
        print("FAIL reject accepted: empty input")
        fails += 1
    except error:
        rejects += 1
    try:
        _ = decode(_unhex("0400000000"))
        print("FAIL reject accepted: length shorter than minimum")
        fails += 1
    except error:
        rejects += 1
    try:
        _ = decode(_unhex("630000001061000100000000"))
        print("FAIL reject accepted: length mismatch")
        fails += 1
    except error:
        rejects += 1
    try:
        _ = decode(_unhex("0c00000010610001000000"))
        print("FAIL reject accepted: truncated document")
        fails += 1
    except error:
        rejects += 1
    try:
        _ = decode(_unhex("14000000076f0000000000000000000000000000"))
        print("FAIL reject accepted: ObjectId policy")
        fails += 1
    except error:
        rejects += 1
    try:
        _ = decode(_unhex("1100000009647400000000000000000000"))
        print("FAIL reject accepted: datetime policy")
        fails += 1
    except error:
        rejects += 1
    try:
        _ = decode(_unhex("0e00000005620001000000004100"))
        print("FAIL reject accepted: binary policy")
        fails += 1
    except error:
        rejects += 1
    try:
        _ = decode(_unhex("180000001364000000000000000000000000000000000000"))
        print("FAIL reject accepted: decimal128 policy")
        fails += 1
    except error:
        rejects += 1
    try:
        _ = decode(_unhex("12000000016e616e00000000000000f87f00"))
        print("FAIL reject accepted: non-finite double")
        fails += 1
    except error:
        rejects += 1
    try:
        _ = decode(_unhex("1200000001696e6600000000000000f07f00"))
        print("FAIL reject accepted: infinite double")
        fails += 1
    except error:
        rejects += 1
    try:
        _ = decode(_unhex("090000000862000200"))
        print("FAIL reject accepted: bool byte 0x02")
        fails += 1
    except error:
        rejects += 1
    try:
        _ = decode(_unhex("0c000000106100010000000000"))
        print("FAIL reject accepted: trailing bytes")
        fails += 1
    except error:
        rejects += 1
    try:
        _ = decode(_unhex("0c000000106e6f7465726d00"))
        print("FAIL reject accepted: unterminated name")
        fails += 1
    except error:
        rejects += 1
    try:
        _ = bson_dumps(loads(String("[1,2]")))
        print("FAIL encode-reject accepted: array root")
        fails += 1
    except error:
        rejects += 1
    try:
        _ = bson_dumps(loads(String('"scalar"')))
        print("FAIL encode-reject accepted: scalar root")
        fails += 1
    except error:
        rejects += 1
    try:
        _ = bson_dumps(loads(String('{"u":18446744073709551615}')))
        print("FAIL encode-reject accepted: uint64 beyond Int64")
        fails += 1
    except error:
        rejects += 1

    print(
        "bson: accepts=",
        accepts,
        " encodes=",
        encodes,
        " roundtrips=",
        roundtrips,
        " rejects=",
        rejects,
        " fails=",
        fails,
    )
    if fails > 0:
        raise Error("BSON VECTORS FAILED")
    print("BSON OK")
