# GENERATED by tests/gen_cbor_vectors.py — do not edit by hand.
# Regenerate: python3 tests/gen_cbor_vectors.py && pixi run format
# CBOR vectors (RFC 8949 Appendix A subset + policy cases): decodes
# compare dumps text, encodes compare exact shortest-form bytes,
# accepts round-trip encode→decode, rejects must raise.

from cbor import decode
from cbor import dumps as cbor_dumps
from json import dumps, loads


def _unhex(hex: String) raises -> List[UInt8]:
    var out = List[UInt8](capacity=hex.byte_length() // 2)
    var chars = hex.as_bytes()
    var i = 0
    while i + 1 < len(chars):
        out.append(UInt8((_nib(chars[i]) << 4) | _nib(chars[i + 1])))
        i += 2
    return out^


def _nib(c: UInt8) raises -> Int:
    if c >= UInt8(ord("0")) and c <= UInt8(ord("9")):
        return Int(c - UInt8(ord("0")))
    return Int(c - UInt8(ord("a"))) + 10


def _to_hex(data: List[UInt8]) -> String:
    comptime HEX = "0123456789abcdef"
    var hb = HEX.as_bytes()
    var out = String("")
    for i in range(len(data)):
        out += chr(Int(hb[Int((data[i] >> 4) & 15)]))
        out += chr(Int(hb[Int(data[i] & 15)]))
    return out^


def main() raises:
    var fails = 0
    var accepts = 0
    var rejects = 0
    var encodes = 0
    var roundtrips = 0

    try:
        var d = decode(_unhex("00"))
        if dumps(d) == "0":
            accepts += 1
        else:
            print("FAIL accept:", "00", "got", dumps(d))
            fails += 1
    except error:
        print("FAIL accept raised:", "00", String(error))
        fails += 1
    try:
        var d = decode(_unhex("01"))
        if dumps(d) == "1":
            accepts += 1
        else:
            print("FAIL accept:", "01", "got", dumps(d))
            fails += 1
    except error:
        print("FAIL accept raised:", "01", String(error))
        fails += 1
    try:
        var d = decode(_unhex("0a"))
        if dumps(d) == "10":
            accepts += 1
        else:
            print("FAIL accept:", "0a", "got", dumps(d))
            fails += 1
    except error:
        print("FAIL accept raised:", "0a", String(error))
        fails += 1
    try:
        var d = decode(_unhex("17"))
        if dumps(d) == "23":
            accepts += 1
        else:
            print("FAIL accept:", "17", "got", dumps(d))
            fails += 1
    except error:
        print("FAIL accept raised:", "17", String(error))
        fails += 1
    try:
        var d = decode(_unhex("1818"))
        if dumps(d) == "24":
            accepts += 1
        else:
            print("FAIL accept:", "1818", "got", dumps(d))
            fails += 1
    except error:
        print("FAIL accept raised:", "1818", String(error))
        fails += 1
    try:
        var d = decode(_unhex("1819"))
        if dumps(d) == "25":
            accepts += 1
        else:
            print("FAIL accept:", "1819", "got", dumps(d))
            fails += 1
    except error:
        print("FAIL accept raised:", "1819", String(error))
        fails += 1
    try:
        var d = decode(_unhex("1864"))
        if dumps(d) == "100":
            accepts += 1
        else:
            print("FAIL accept:", "1864", "got", dumps(d))
            fails += 1
    except error:
        print("FAIL accept raised:", "1864", String(error))
        fails += 1
    try:
        var d = decode(_unhex("1903e8"))
        if dumps(d) == "1000":
            accepts += 1
        else:
            print("FAIL accept:", "1903e8", "got", dumps(d))
            fails += 1
    except error:
        print("FAIL accept raised:", "1903e8", String(error))
        fails += 1
    try:
        var d = decode(_unhex("1a000f4240"))
        if dumps(d) == "1000000":
            accepts += 1
        else:
            print("FAIL accept:", "1a000f4240", "got", dumps(d))
            fails += 1
    except error:
        print("FAIL accept raised:", "1a000f4240", String(error))
        fails += 1
    try:
        var d = decode(_unhex("1b000000e8d4a51000"))
        if dumps(d) == "1000000000000":
            accepts += 1
        else:
            print("FAIL accept:", "1b000000e8d4a51000", "got", dumps(d))
            fails += 1
    except error:
        print("FAIL accept raised:", "1b000000e8d4a51000", String(error))
        fails += 1
    try:
        var d = decode(_unhex("1bffffffffffffffff"))
        if dumps(d) == "18446744073709551615":
            accepts += 1
        else:
            print("FAIL accept:", "1bffffffffffffffff", "got", dumps(d))
            fails += 1
    except error:
        print("FAIL accept raised:", "1bffffffffffffffff", String(error))
        fails += 1
    try:
        var d = decode(_unhex("20"))
        if dumps(d) == "-1":
            accepts += 1
        else:
            print("FAIL accept:", "20", "got", dumps(d))
            fails += 1
    except error:
        print("FAIL accept raised:", "20", String(error))
        fails += 1
    try:
        var d = decode(_unhex("29"))
        if dumps(d) == "-10":
            accepts += 1
        else:
            print("FAIL accept:", "29", "got", dumps(d))
            fails += 1
    except error:
        print("FAIL accept raised:", "29", String(error))
        fails += 1
    try:
        var d = decode(_unhex("3863"))
        if dumps(d) == "-100":
            accepts += 1
        else:
            print("FAIL accept:", "3863", "got", dumps(d))
            fails += 1
    except error:
        print("FAIL accept raised:", "3863", String(error))
        fails += 1
    try:
        var d = decode(_unhex("3903e7"))
        if dumps(d) == "-1000":
            accepts += 1
        else:
            print("FAIL accept:", "3903e7", "got", dumps(d))
            fails += 1
    except error:
        print("FAIL accept raised:", "3903e7", String(error))
        fails += 1
    try:
        var d = decode(_unhex("3b7fffffffffffffff"))
        if dumps(d) == "-9223372036854775808":
            accepts += 1
        else:
            print("FAIL accept:", "3b7fffffffffffffff", "got", dumps(d))
            fails += 1
    except error:
        print("FAIL accept raised:", "3b7fffffffffffffff", String(error))
        fails += 1
    try:
        var d = decode(_unhex("f4"))
        if dumps(d) == "false":
            accepts += 1
        else:
            print("FAIL accept:", "f4", "got", dumps(d))
            fails += 1
    except error:
        print("FAIL accept raised:", "f4", String(error))
        fails += 1
    try:
        var d = decode(_unhex("f5"))
        if dumps(d) == "true":
            accepts += 1
        else:
            print("FAIL accept:", "f5", "got", dumps(d))
            fails += 1
    except error:
        print("FAIL accept raised:", "f5", String(error))
        fails += 1
    try:
        var d = decode(_unhex("f6"))
        if dumps(d) == "null":
            accepts += 1
        else:
            print("FAIL accept:", "f6", "got", dumps(d))
            fails += 1
    except error:
        print("FAIL accept raised:", "f6", String(error))
        fails += 1
    try:
        var d = decode(_unhex("f90000"))
        if dumps(d) == "0.0":
            accepts += 1
        else:
            print("FAIL accept:", "f90000", "got", dumps(d))
            fails += 1
    except error:
        print("FAIL accept raised:", "f90000", String(error))
        fails += 1
    try:
        var d = decode(_unhex("f93c00"))
        if dumps(d) == "1.0":
            accepts += 1
        else:
            print("FAIL accept:", "f93c00", "got", dumps(d))
            fails += 1
    except error:
        print("FAIL accept raised:", "f93c00", String(error))
        fails += 1
    try:
        var d = decode(_unhex("f93e00"))
        if dumps(d) == "1.5":
            accepts += 1
        else:
            print("FAIL accept:", "f93e00", "got", dumps(d))
            fails += 1
    except error:
        print("FAIL accept raised:", "f93e00", String(error))
        fails += 1
    try:
        var d = decode(_unhex("f97bff"))
        if dumps(d) == "65504.0":
            accepts += 1
        else:
            print("FAIL accept:", "f97bff", "got", dumps(d))
            fails += 1
    except error:
        print("FAIL accept raised:", "f97bff", String(error))
        fails += 1
    try:
        var d = decode(_unhex("fa47c35000"))
        if dumps(d) == "100000.0":
            accepts += 1
        else:
            print("FAIL accept:", "fa47c35000", "got", dumps(d))
            fails += 1
    except error:
        print("FAIL accept raised:", "fa47c35000", String(error))
        fails += 1
    try:
        var d = decode(_unhex("fb3ff199999999999a"))
        if dumps(d) == "1.1":
            accepts += 1
        else:
            print("FAIL accept:", "fb3ff199999999999a", "got", dumps(d))
            fails += 1
    except error:
        print("FAIL accept raised:", "fb3ff199999999999a", String(error))
        fails += 1
    try:
        var d = decode(_unhex("fb7e37e43c8800759c"))
        if dumps(d) == "1e+300":
            accepts += 1
        else:
            print("FAIL accept:", "fb7e37e43c8800759c", "got", dumps(d))
            fails += 1
    except error:
        print("FAIL accept raised:", "fb7e37e43c8800759c", String(error))
        fails += 1
    try:
        var d = decode(_unhex("60"))
        if dumps(d) == '""':
            accepts += 1
        else:
            print("FAIL accept:", "60", "got", dumps(d))
            fails += 1
    except error:
        print("FAIL accept raised:", "60", String(error))
        fails += 1
    try:
        var d = decode(_unhex("6161"))
        if dumps(d) == '"a"':
            accepts += 1
        else:
            print("FAIL accept:", "6161", "got", dumps(d))
            fails += 1
    except error:
        print("FAIL accept raised:", "6161", String(error))
        fails += 1
    try:
        var d = decode(_unhex("6449455446"))
        if dumps(d) == '"IETF"':
            accepts += 1
        else:
            print("FAIL accept:", "6449455446", "got", dumps(d))
            fails += 1
    except error:
        print("FAIL accept raised:", "6449455446", String(error))
        fails += 1
    try:
        var d = decode(_unhex("62225c"))
        if dumps(d) == '"\\"\\\\"':
            accepts += 1
        else:
            print("FAIL accept:", "62225c", "got", dumps(d))
            fails += 1
    except error:
        print("FAIL accept raised:", "62225c", String(error))
        fails += 1
    try:
        var d = decode(_unhex("62c3bc"))
        if dumps(d) == '"ü"':
            accepts += 1
        else:
            print("FAIL accept:", "62c3bc", "got", dumps(d))
            fails += 1
    except error:
        print("FAIL accept raised:", "62c3bc", String(error))
        fails += 1
    try:
        var d = decode(_unhex("63e6b0b4"))
        if dumps(d) == '"水"':
            accepts += 1
        else:
            print("FAIL accept:", "63e6b0b4", "got", dumps(d))
            fails += 1
    except error:
        print("FAIL accept raised:", "63e6b0b4", String(error))
        fails += 1
    try:
        var d = decode(_unhex("80"))
        if dumps(d) == "[]":
            accepts += 1
        else:
            print("FAIL accept:", "80", "got", dumps(d))
            fails += 1
    except error:
        print("FAIL accept raised:", "80", String(error))
        fails += 1
    try:
        var d = decode(_unhex("83010203"))
        if dumps(d) == "[1,2,3]":
            accepts += 1
        else:
            print("FAIL accept:", "83010203", "got", dumps(d))
            fails += 1
    except error:
        print("FAIL accept raised:", "83010203", String(error))
        fails += 1
    try:
        var d = decode(_unhex("8301820203820405"))
        if dumps(d) == "[1,[2,3],[4,5]]":
            accepts += 1
        else:
            print("FAIL accept:", "8301820203820405", "got", dumps(d))
            fails += 1
    except error:
        print("FAIL accept raised:", "8301820203820405", String(error))
        fails += 1
    try:
        var d = decode(
            _unhex("98190102030405060708090a0b0c0d0e0f101112131415161718181819")
        )
        if (
            dumps(d)
            == "[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]"
        ):
            accepts += 1
        else:
            print(
                "FAIL accept:",
                "98190102030405060708090a0b0c0d0e0f101112131415161718181819",
                "got",
                dumps(d),
            )
            fails += 1
    except error:
        print(
            "FAIL accept raised:",
            "98190102030405060708090a0b0c0d0e0f101112131415161718181819",
            String(error),
        )
        fails += 1
    try:
        var d = decode(_unhex("a0"))
        if dumps(d) == "{}":
            accepts += 1
        else:
            print("FAIL accept:", "a0", "got", dumps(d))
            fails += 1
    except error:
        print("FAIL accept raised:", "a0", String(error))
        fails += 1
    try:
        var d = decode(_unhex("a26161016162820203"))
        if dumps(d) == '{"a":1,"b":[2,3]}':
            accepts += 1
        else:
            print("FAIL accept:", "a26161016162820203", "got", dumps(d))
            fails += 1
    except error:
        print("FAIL accept raised:", "a26161016162820203", String(error))
        fails += 1
    try:
        var d = decode(_unhex("9f0102ff"))
        if dumps(d) == "[1,2]":
            accepts += 1
        else:
            print("FAIL accept:", "9f0102ff", "got", dumps(d))
            fails += 1
    except error:
        print("FAIL accept raised:", "9f0102ff", String(error))
        fails += 1
    try:
        var d = decode(_unhex("9fff"))
        if dumps(d) == "[]":
            accepts += 1
        else:
            print("FAIL accept:", "9fff", "got", dumps(d))
            fails += 1
    except error:
        print("FAIL accept raised:", "9fff", String(error))
        fails += 1
    try:
        var d = decode(_unhex("bf616b07ff"))
        if dumps(d) == '{"k":7}':
            accepts += 1
        else:
            print("FAIL accept:", "bf616b07ff", "got", dumps(d))
            fails += 1
    except error:
        print("FAIL accept raised:", "bf616b07ff", String(error))
        fails += 1
    try:
        var d = decode(_unhex("7f657374726561646d696e67ff"))
        if dumps(d) == '"streaming"':
            accepts += 1
        else:
            print("FAIL accept:", "7f657374726561646d696e67ff", "got", dumps(d))
            fails += 1
    except error:
        print(
            "FAIL accept raised:", "7f657374726561646d696e67ff", String(error)
        )
        fails += 1
    try:
        var d = decode(_unhex("9f9f01ffff"))
        if dumps(d) == "[[1]]":
            accepts += 1
        else:
            print("FAIL accept:", "9f9f01ffff", "got", dumps(d))
            fails += 1
    except error:
        print("FAIL accept raised:", "9f9f01ffff", String(error))
        fails += 1

    try:
        var e = cbor_dumps(loads(String("0")))
        if _to_hex(e) == "00":
            encodes += 1
        else:
            print("FAIL encode:", "0", "got", _to_hex(e))
            fails += 1
    except error:
        print("FAIL encode raised:", "0", String(error))
        fails += 1
    try:
        var e = cbor_dumps(loads(String("23")))
        if _to_hex(e) == "17":
            encodes += 1
        else:
            print("FAIL encode:", "23", "got", _to_hex(e))
            fails += 1
    except error:
        print("FAIL encode raised:", "23", String(error))
        fails += 1
    try:
        var e = cbor_dumps(loads(String("24")))
        if _to_hex(e) == "1818":
            encodes += 1
        else:
            print("FAIL encode:", "24", "got", _to_hex(e))
            fails += 1
    except error:
        print("FAIL encode raised:", "24", String(error))
        fails += 1
    try:
        var e = cbor_dumps(loads(String("500")))
        if _to_hex(e) == "1901f4":
            encodes += 1
        else:
            print("FAIL encode:", "500", "got", _to_hex(e))
            fails += 1
    except error:
        print("FAIL encode raised:", "500", String(error))
        fails += 1
    try:
        var e = cbor_dumps(loads(String("1000000")))
        if _to_hex(e) == "1a000f4240":
            encodes += 1
        else:
            print("FAIL encode:", "1000000", "got", _to_hex(e))
            fails += 1
    except error:
        print("FAIL encode raised:", "1000000", String(error))
        fails += 1
    try:
        var e = cbor_dumps(loads(String("18446744073709551615")))
        if _to_hex(e) == "1bffffffffffffffff":
            encodes += 1
        else:
            print("FAIL encode:", "18446744073709551615", "got", _to_hex(e))
            fails += 1
    except error:
        print("FAIL encode raised:", "18446744073709551615", String(error))
        fails += 1
    try:
        var e = cbor_dumps(loads(String("-1")))
        if _to_hex(e) == "20":
            encodes += 1
        else:
            print("FAIL encode:", "-1", "got", _to_hex(e))
            fails += 1
    except error:
        print("FAIL encode raised:", "-1", String(error))
        fails += 1
    try:
        var e = cbor_dumps(loads(String("-1000")))
        if _to_hex(e) == "3903e7":
            encodes += 1
        else:
            print("FAIL encode:", "-1000", "got", _to_hex(e))
            fails += 1
    except error:
        print("FAIL encode raised:", "-1000", String(error))
        fails += 1
    try:
        var e = cbor_dumps(loads(String("-9223372036854775808")))
        if _to_hex(e) == "3b7fffffffffffffff":
            encodes += 1
        else:
            print("FAIL encode:", "-9223372036854775808", "got", _to_hex(e))
            fails += 1
    except error:
        print("FAIL encode raised:", "-9223372036854775808", String(error))
        fails += 1
    try:
        var e = cbor_dumps(loads(String("1.5")))
        if _to_hex(e) == "fb3ff8000000000000":
            encodes += 1
        else:
            print("FAIL encode:", "1.5", "got", _to_hex(e))
            fails += 1
    except error:
        print("FAIL encode raised:", "1.5", String(error))
        fails += 1
    try:
        var e = cbor_dumps(loads(String('"a"')))
        if _to_hex(e) == "6161":
            encodes += 1
        else:
            print("FAIL encode:", '"a"', "got", _to_hex(e))
            fails += 1
    except error:
        print("FAIL encode raised:", '"a"', String(error))
        fails += 1
    try:
        var e = cbor_dumps(loads(String("[1,2]")))
        if _to_hex(e) == "820102":
            encodes += 1
        else:
            print("FAIL encode:", "[1,2]", "got", _to_hex(e))
            fails += 1
    except error:
        print("FAIL encode raised:", "[1,2]", String(error))
        fails += 1
    try:
        var e = cbor_dumps(loads(String('{"a":1}')))
        if _to_hex(e) == "a1616101":
            encodes += 1
        else:
            print("FAIL encode:", '{"a":1}', "got", _to_hex(e))
            fails += 1
    except error:
        print("FAIL encode raised:", '{"a":1}', String(error))
        fails += 1
    try:
        var e = cbor_dumps(loads(String("null")))
        if _to_hex(e) == "f6":
            encodes += 1
        else:
            print("FAIL encode:", "null", "got", _to_hex(e))
            fails += 1
    except error:
        print("FAIL encode raised:", "null", String(error))
        fails += 1
    try:
        var e = cbor_dumps(loads(String("true")))
        if _to_hex(e) == "f5":
            encodes += 1
        else:
            print("FAIL encode:", "true", "got", _to_hex(e))
            fails += 1
    except error:
        print("FAIL encode raised:", "true", String(error))
        fails += 1
    try:
        var e = cbor_dumps(loads(String("false")))
        if _to_hex(e) == "f4":
            encodes += 1
        else:
            print("FAIL encode:", "false", "got", _to_hex(e))
            fails += 1
    except error:
        print("FAIL encode raised:", "false", String(error))
        fails += 1
    try:
        var e = cbor_dumps(loads(String('{"nest":[[]]}')))
        if _to_hex(e) == "a1646e6573748180":
            encodes += 1
        else:
            print("FAIL encode:", '{"nest":[[]]}', "got", _to_hex(e))
            fails += 1
    except error:
        print("FAIL encode raised:", '{"nest":[[]]}', String(error))
        fails += 1

    try:
        var r1 = decode(_unhex("00"))
        var r2 = decode(cbor_dumps(r1))
        if dumps(r2) == "0":
            roundtrips += 1
        else:
            print("FAIL roundtrip:", "00", "got", dumps(r2))
            fails += 1
    except error:
        print("FAIL roundtrip raised:", "00", String(error))
        fails += 1
    try:
        var r1 = decode(_unhex("01"))
        var r2 = decode(cbor_dumps(r1))
        if dumps(r2) == "1":
            roundtrips += 1
        else:
            print("FAIL roundtrip:", "01", "got", dumps(r2))
            fails += 1
    except error:
        print("FAIL roundtrip raised:", "01", String(error))
        fails += 1
    try:
        var r1 = decode(_unhex("0a"))
        var r2 = decode(cbor_dumps(r1))
        if dumps(r2) == "10":
            roundtrips += 1
        else:
            print("FAIL roundtrip:", "0a", "got", dumps(r2))
            fails += 1
    except error:
        print("FAIL roundtrip raised:", "0a", String(error))
        fails += 1
    try:
        var r1 = decode(_unhex("17"))
        var r2 = decode(cbor_dumps(r1))
        if dumps(r2) == "23":
            roundtrips += 1
        else:
            print("FAIL roundtrip:", "17", "got", dumps(r2))
            fails += 1
    except error:
        print("FAIL roundtrip raised:", "17", String(error))
        fails += 1
    try:
        var r1 = decode(_unhex("1818"))
        var r2 = decode(cbor_dumps(r1))
        if dumps(r2) == "24":
            roundtrips += 1
        else:
            print("FAIL roundtrip:", "1818", "got", dumps(r2))
            fails += 1
    except error:
        print("FAIL roundtrip raised:", "1818", String(error))
        fails += 1
    try:
        var r1 = decode(_unhex("1819"))
        var r2 = decode(cbor_dumps(r1))
        if dumps(r2) == "25":
            roundtrips += 1
        else:
            print("FAIL roundtrip:", "1819", "got", dumps(r2))
            fails += 1
    except error:
        print("FAIL roundtrip raised:", "1819", String(error))
        fails += 1
    try:
        var r1 = decode(_unhex("1864"))
        var r2 = decode(cbor_dumps(r1))
        if dumps(r2) == "100":
            roundtrips += 1
        else:
            print("FAIL roundtrip:", "1864", "got", dumps(r2))
            fails += 1
    except error:
        print("FAIL roundtrip raised:", "1864", String(error))
        fails += 1
    try:
        var r1 = decode(_unhex("1903e8"))
        var r2 = decode(cbor_dumps(r1))
        if dumps(r2) == "1000":
            roundtrips += 1
        else:
            print("FAIL roundtrip:", "1903e8", "got", dumps(r2))
            fails += 1
    except error:
        print("FAIL roundtrip raised:", "1903e8", String(error))
        fails += 1
    try:
        var r1 = decode(_unhex("1a000f4240"))
        var r2 = decode(cbor_dumps(r1))
        if dumps(r2) == "1000000":
            roundtrips += 1
        else:
            print("FAIL roundtrip:", "1a000f4240", "got", dumps(r2))
            fails += 1
    except error:
        print("FAIL roundtrip raised:", "1a000f4240", String(error))
        fails += 1
    try:
        var r1 = decode(_unhex("1b000000e8d4a51000"))
        var r2 = decode(cbor_dumps(r1))
        if dumps(r2) == "1000000000000":
            roundtrips += 1
        else:
            print("FAIL roundtrip:", "1b000000e8d4a51000", "got", dumps(r2))
            fails += 1
    except error:
        print("FAIL roundtrip raised:", "1b000000e8d4a51000", String(error))
        fails += 1
    try:
        var r1 = decode(_unhex("1bffffffffffffffff"))
        var r2 = decode(cbor_dumps(r1))
        if dumps(r2) == "18446744073709551615":
            roundtrips += 1
        else:
            print("FAIL roundtrip:", "1bffffffffffffffff", "got", dumps(r2))
            fails += 1
    except error:
        print("FAIL roundtrip raised:", "1bffffffffffffffff", String(error))
        fails += 1
    try:
        var r1 = decode(_unhex("20"))
        var r2 = decode(cbor_dumps(r1))
        if dumps(r2) == "-1":
            roundtrips += 1
        else:
            print("FAIL roundtrip:", "20", "got", dumps(r2))
            fails += 1
    except error:
        print("FAIL roundtrip raised:", "20", String(error))
        fails += 1
    try:
        var r1 = decode(_unhex("29"))
        var r2 = decode(cbor_dumps(r1))
        if dumps(r2) == "-10":
            roundtrips += 1
        else:
            print("FAIL roundtrip:", "29", "got", dumps(r2))
            fails += 1
    except error:
        print("FAIL roundtrip raised:", "29", String(error))
        fails += 1
    try:
        var r1 = decode(_unhex("3863"))
        var r2 = decode(cbor_dumps(r1))
        if dumps(r2) == "-100":
            roundtrips += 1
        else:
            print("FAIL roundtrip:", "3863", "got", dumps(r2))
            fails += 1
    except error:
        print("FAIL roundtrip raised:", "3863", String(error))
        fails += 1
    try:
        var r1 = decode(_unhex("3903e7"))
        var r2 = decode(cbor_dumps(r1))
        if dumps(r2) == "-1000":
            roundtrips += 1
        else:
            print("FAIL roundtrip:", "3903e7", "got", dumps(r2))
            fails += 1
    except error:
        print("FAIL roundtrip raised:", "3903e7", String(error))
        fails += 1
    try:
        var r1 = decode(_unhex("3b7fffffffffffffff"))
        var r2 = decode(cbor_dumps(r1))
        if dumps(r2) == "-9223372036854775808":
            roundtrips += 1
        else:
            print("FAIL roundtrip:", "3b7fffffffffffffff", "got", dumps(r2))
            fails += 1
    except error:
        print("FAIL roundtrip raised:", "3b7fffffffffffffff", String(error))
        fails += 1
    try:
        var r1 = decode(_unhex("f4"))
        var r2 = decode(cbor_dumps(r1))
        if dumps(r2) == "false":
            roundtrips += 1
        else:
            print("FAIL roundtrip:", "f4", "got", dumps(r2))
            fails += 1
    except error:
        print("FAIL roundtrip raised:", "f4", String(error))
        fails += 1
    try:
        var r1 = decode(_unhex("f5"))
        var r2 = decode(cbor_dumps(r1))
        if dumps(r2) == "true":
            roundtrips += 1
        else:
            print("FAIL roundtrip:", "f5", "got", dumps(r2))
            fails += 1
    except error:
        print("FAIL roundtrip raised:", "f5", String(error))
        fails += 1
    try:
        var r1 = decode(_unhex("f6"))
        var r2 = decode(cbor_dumps(r1))
        if dumps(r2) == "null":
            roundtrips += 1
        else:
            print("FAIL roundtrip:", "f6", "got", dumps(r2))
            fails += 1
    except error:
        print("FAIL roundtrip raised:", "f6", String(error))
        fails += 1
    try:
        var r1 = decode(_unhex("f90000"))
        var r2 = decode(cbor_dumps(r1))
        if dumps(r2) == "0.0":
            roundtrips += 1
        else:
            print("FAIL roundtrip:", "f90000", "got", dumps(r2))
            fails += 1
    except error:
        print("FAIL roundtrip raised:", "f90000", String(error))
        fails += 1
    try:
        var r1 = decode(_unhex("f93c00"))
        var r2 = decode(cbor_dumps(r1))
        if dumps(r2) == "1.0":
            roundtrips += 1
        else:
            print("FAIL roundtrip:", "f93c00", "got", dumps(r2))
            fails += 1
    except error:
        print("FAIL roundtrip raised:", "f93c00", String(error))
        fails += 1
    try:
        var r1 = decode(_unhex("f93e00"))
        var r2 = decode(cbor_dumps(r1))
        if dumps(r2) == "1.5":
            roundtrips += 1
        else:
            print("FAIL roundtrip:", "f93e00", "got", dumps(r2))
            fails += 1
    except error:
        print("FAIL roundtrip raised:", "f93e00", String(error))
        fails += 1
    try:
        var r1 = decode(_unhex("f97bff"))
        var r2 = decode(cbor_dumps(r1))
        if dumps(r2) == "65504.0":
            roundtrips += 1
        else:
            print("FAIL roundtrip:", "f97bff", "got", dumps(r2))
            fails += 1
    except error:
        print("FAIL roundtrip raised:", "f97bff", String(error))
        fails += 1
    try:
        var r1 = decode(_unhex("fa47c35000"))
        var r2 = decode(cbor_dumps(r1))
        if dumps(r2) == "100000.0":
            roundtrips += 1
        else:
            print("FAIL roundtrip:", "fa47c35000", "got", dumps(r2))
            fails += 1
    except error:
        print("FAIL roundtrip raised:", "fa47c35000", String(error))
        fails += 1
    try:
        var r1 = decode(_unhex("fb3ff199999999999a"))
        var r2 = decode(cbor_dumps(r1))
        if dumps(r2) == "1.1":
            roundtrips += 1
        else:
            print("FAIL roundtrip:", "fb3ff199999999999a", "got", dumps(r2))
            fails += 1
    except error:
        print("FAIL roundtrip raised:", "fb3ff199999999999a", String(error))
        fails += 1
    try:
        var r1 = decode(_unhex("fb7e37e43c8800759c"))
        var r2 = decode(cbor_dumps(r1))
        if dumps(r2) == "1e+300":
            roundtrips += 1
        else:
            print("FAIL roundtrip:", "fb7e37e43c8800759c", "got", dumps(r2))
            fails += 1
    except error:
        print("FAIL roundtrip raised:", "fb7e37e43c8800759c", String(error))
        fails += 1
    try:
        var r1 = decode(_unhex("60"))
        var r2 = decode(cbor_dumps(r1))
        if dumps(r2) == '""':
            roundtrips += 1
        else:
            print("FAIL roundtrip:", "60", "got", dumps(r2))
            fails += 1
    except error:
        print("FAIL roundtrip raised:", "60", String(error))
        fails += 1
    try:
        var r1 = decode(_unhex("6161"))
        var r2 = decode(cbor_dumps(r1))
        if dumps(r2) == '"a"':
            roundtrips += 1
        else:
            print("FAIL roundtrip:", "6161", "got", dumps(r2))
            fails += 1
    except error:
        print("FAIL roundtrip raised:", "6161", String(error))
        fails += 1
    try:
        var r1 = decode(_unhex("6449455446"))
        var r2 = decode(cbor_dumps(r1))
        if dumps(r2) == '"IETF"':
            roundtrips += 1
        else:
            print("FAIL roundtrip:", "6449455446", "got", dumps(r2))
            fails += 1
    except error:
        print("FAIL roundtrip raised:", "6449455446", String(error))
        fails += 1
    try:
        var r1 = decode(_unhex("62225c"))
        var r2 = decode(cbor_dumps(r1))
        if dumps(r2) == '"\\"\\\\"':
            roundtrips += 1
        else:
            print("FAIL roundtrip:", "62225c", "got", dumps(r2))
            fails += 1
    except error:
        print("FAIL roundtrip raised:", "62225c", String(error))
        fails += 1
    try:
        var r1 = decode(_unhex("62c3bc"))
        var r2 = decode(cbor_dumps(r1))
        if dumps(r2) == '"ü"':
            roundtrips += 1
        else:
            print("FAIL roundtrip:", "62c3bc", "got", dumps(r2))
            fails += 1
    except error:
        print("FAIL roundtrip raised:", "62c3bc", String(error))
        fails += 1
    try:
        var r1 = decode(_unhex("63e6b0b4"))
        var r2 = decode(cbor_dumps(r1))
        if dumps(r2) == '"水"':
            roundtrips += 1
        else:
            print("FAIL roundtrip:", "63e6b0b4", "got", dumps(r2))
            fails += 1
    except error:
        print("FAIL roundtrip raised:", "63e6b0b4", String(error))
        fails += 1
    try:
        var r1 = decode(_unhex("80"))
        var r2 = decode(cbor_dumps(r1))
        if dumps(r2) == "[]":
            roundtrips += 1
        else:
            print("FAIL roundtrip:", "80", "got", dumps(r2))
            fails += 1
    except error:
        print("FAIL roundtrip raised:", "80", String(error))
        fails += 1
    try:
        var r1 = decode(_unhex("83010203"))
        var r2 = decode(cbor_dumps(r1))
        if dumps(r2) == "[1,2,3]":
            roundtrips += 1
        else:
            print("FAIL roundtrip:", "83010203", "got", dumps(r2))
            fails += 1
    except error:
        print("FAIL roundtrip raised:", "83010203", String(error))
        fails += 1
    try:
        var r1 = decode(_unhex("8301820203820405"))
        var r2 = decode(cbor_dumps(r1))
        if dumps(r2) == "[1,[2,3],[4,5]]":
            roundtrips += 1
        else:
            print("FAIL roundtrip:", "8301820203820405", "got", dumps(r2))
            fails += 1
    except error:
        print("FAIL roundtrip raised:", "8301820203820405", String(error))
        fails += 1
    try:
        var r1 = decode(
            _unhex("98190102030405060708090a0b0c0d0e0f101112131415161718181819")
        )
        var r2 = decode(cbor_dumps(r1))
        if (
            dumps(r2)
            == "[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]"
        ):
            roundtrips += 1
        else:
            print(
                "FAIL roundtrip:",
                "98190102030405060708090a0b0c0d0e0f101112131415161718181819",
                "got",
                dumps(r2),
            )
            fails += 1
    except error:
        print(
            "FAIL roundtrip raised:",
            "98190102030405060708090a0b0c0d0e0f101112131415161718181819",
            String(error),
        )
        fails += 1
    try:
        var r1 = decode(_unhex("a0"))
        var r2 = decode(cbor_dumps(r1))
        if dumps(r2) == "{}":
            roundtrips += 1
        else:
            print("FAIL roundtrip:", "a0", "got", dumps(r2))
            fails += 1
    except error:
        print("FAIL roundtrip raised:", "a0", String(error))
        fails += 1
    try:
        var r1 = decode(_unhex("a26161016162820203"))
        var r2 = decode(cbor_dumps(r1))
        if dumps(r2) == '{"a":1,"b":[2,3]}':
            roundtrips += 1
        else:
            print("FAIL roundtrip:", "a26161016162820203", "got", dumps(r2))
            fails += 1
    except error:
        print("FAIL roundtrip raised:", "a26161016162820203", String(error))
        fails += 1
    try:
        var r1 = decode(_unhex("9f0102ff"))
        var r2 = decode(cbor_dumps(r1))
        if dumps(r2) == "[1,2]":
            roundtrips += 1
        else:
            print("FAIL roundtrip:", "9f0102ff", "got", dumps(r2))
            fails += 1
    except error:
        print("FAIL roundtrip raised:", "9f0102ff", String(error))
        fails += 1
    try:
        var r1 = decode(_unhex("9fff"))
        var r2 = decode(cbor_dumps(r1))
        if dumps(r2) == "[]":
            roundtrips += 1
        else:
            print("FAIL roundtrip:", "9fff", "got", dumps(r2))
            fails += 1
    except error:
        print("FAIL roundtrip raised:", "9fff", String(error))
        fails += 1
    try:
        var r1 = decode(_unhex("bf616b07ff"))
        var r2 = decode(cbor_dumps(r1))
        if dumps(r2) == '{"k":7}':
            roundtrips += 1
        else:
            print("FAIL roundtrip:", "bf616b07ff", "got", dumps(r2))
            fails += 1
    except error:
        print("FAIL roundtrip raised:", "bf616b07ff", String(error))
        fails += 1
    try:
        var r1 = decode(_unhex("7f657374726561646d696e67ff"))
        var r2 = decode(cbor_dumps(r1))
        if dumps(r2) == '"streaming"':
            roundtrips += 1
        else:
            print(
                "FAIL roundtrip:",
                "7f657374726561646d696e67ff",
                "got",
                dumps(r2),
            )
            fails += 1
    except error:
        print(
            "FAIL roundtrip raised:",
            "7f657374726561646d696e67ff",
            String(error),
        )
        fails += 1
    try:
        var r1 = decode(_unhex("9f9f01ffff"))
        var r2 = decode(cbor_dumps(r1))
        if dumps(r2) == "[[1]]":
            roundtrips += 1
        else:
            print("FAIL roundtrip:", "9f9f01ffff", "got", dumps(r2))
            fails += 1
    except error:
        print("FAIL roundtrip raised:", "9f9f01ffff", String(error))
        fails += 1

    try:
        _ = decode(_unhex("40"))
        print("FAIL reject accepted: byte string (major 2)")
        fails += 1
    except error:
        rejects += 1
    try:
        _ = decode(_unhex("c06432303133"))
        print("FAIL reject accepted: tag (major 6)")
        fails += 1
    except error:
        rejects += 1
    try:
        _ = decode(_unhex("f7"))
        print("FAIL reject accepted: undefined")
        fails += 1
    except error:
        rejects += 1
    try:
        _ = decode(_unhex("f0"))
        print("FAIL reject accepted: simple value 16")
        fails += 1
    except error:
        rejects += 1
    try:
        _ = decode(_unhex("f97e00"))
        print("FAIL reject accepted: NaN half")
        fails += 1
    except error:
        rejects += 1
    try:
        _ = decode(_unhex("f97c00"))
        print("FAIL reject accepted: Infinity half")
        fails += 1
    except error:
        rejects += 1
    try:
        _ = decode(_unhex("fbfff0000000000000"))
        print("FAIL reject accepted: -Infinity double")
        fails += 1
    except error:
        rejects += 1
    try:
        _ = decode(_unhex("3bffffffffffffffff"))
        print("FAIL reject accepted: negative below Int64.MIN")
        fails += 1
    except error:
        rejects += 1
    try:
        _ = decode(_unhex("1c"))
        print("FAIL reject accepted: reserved additional info 28")
        fails += 1
    except error:
        rejects += 1
    try:
        _ = decode(_unhex("ff"))
        print("FAIL reject accepted: lone break")
        fails += 1
    except error:
        rejects += 1
    try:
        _ = decode(_unhex("19"))
        print("FAIL reject accepted: truncated argument")
        fails += 1
    except error:
        rejects += 1
    try:
        _ = decode(_unhex("8201"))
        print("FAIL reject accepted: array missing an element")
        fails += 1
    except error:
        rejects += 1
    try:
        _ = decode(_unhex("0102"))
        print("FAIL reject accepted: trailing bytes")
        fails += 1
    except error:
        rejects += 1
    try:
        _ = decode(_unhex(""))
        print("FAIL reject accepted: empty input")
        fails += 1
    except error:
        rejects += 1
    try:
        _ = decode(_unhex("a10102"))
        print("FAIL reject accepted: integer map key (policy)")
        fails += 1
    except error:
        rejects += 1
    try:
        _ = decode(_unhex("7f9fffff"))
        print("FAIL reject accepted: non-text chunk in indefinite text")
        fails += 1
    except error:
        rejects += 1
    try:
        _ = decode(_unhex("bf616bff"))
        print("FAIL reject accepted: break splits a map pair")
        fails += 1
    except error:
        rejects += 1
    try:
        _ = decode(_unhex("9f01"))
        print("FAIL reject accepted: unterminated indefinite array")
        fails += 1
    except error:
        rejects += 1

    print(
        "cbor: accepts=",
        accepts,
        " encodes=",
        encodes,
        " roundtrips=",
        roundtrips,
        " rejects=",
        rejects,
        " fails=",
        fails,
    )
    if fails > 0:
        raise Error("CBOR VECTORS FAILED")
    print("CBOR OK")
