#!/usr/bin/env python3
# BSON differential vectors (bsonspec.org v1.1) — packed BY HAND with struct
# (the packing IS the spec reference). Structural decodes compare `dumps`
# JSON; encodes compare exact bytes; every ACCEPT round-trips through
# encode→decode. Regenerate: python3 tests/gen_bson_vectors.py && pixi run format
import struct

OUT = "tests/bson_generated.mojo"


def h(b: bytes) -> str:
    return b.hex()


def cstr(s: str) -> bytes:
    return s.encode() + b"\x00"


def bstr(s: str) -> bytes:
    raw = s.encode()
    return struct.pack("<i", len(raw) + 1) + raw + b"\x00"


def doc(*elements: bytes) -> bytes:
    body = b"".join(elements)
    return struct.pack("<i", len(body) + 5) + body + b"\x00"


def e_double(name, v):
    return b"\x01" + cstr(name) + struct.pack("<d", v)


def e_string(name, s):
    return b"\x02" + cstr(name) + bstr(s)


def e_doc(name, d):
    return b"\x03" + cstr(name) + d


def e_array(name, d):
    return b"\x04" + cstr(name) + d


def e_bool(name, v):
    return b"\x08" + cstr(name) + (b"\x01" if v else b"\x00")


def e_null(name):
    return b"\x0a" + cstr(name)


def e_i32(name, v):
    return b"\x10" + cstr(name) + struct.pack("<i", v)


def e_i64(name, v):
    return b"\x12" + cstr(name) + struct.pack("<q", v)


ACCEPT = []  # (hex, expected_json)


def acc(b, expected):
    ACCEPT.append((h(b), expected))


acc(doc(), "{}")
acc(doc(e_i32("a", 1)), '{"a":1}')
acc(doc(e_i32("n", -300)), '{"n":-300}')
acc(doc(e_i64("big", 4294967296)), '{"big":4294967296}')
acc(doc(e_i64("min", -9223372036854775808)), '{"min":-9223372036854775808}')
acc(doc(e_double("f", 1.5)), '{"f":1.5}')
acc(doc(e_string("s", "hi")), '{"s":"hi"}')
acc(doc(e_string("u", "héllo")), '{"u":"héllo"}')
acc(doc(e_string("d", 'a"b\n')), '{"d":"a\\"b\\n"}')
acc(doc(e_bool("t", True), e_bool("f", False)), '{"t":true,"f":false}')
acc(doc(e_null("z")), '{"z":null}')
acc(
    doc(e_array("a", doc(e_i32("0", 1), e_i32("1", 2)))),
    '{"a":[1,2]}',
)
acc(
    doc(e_doc("o", doc(e_string("k", "v")))),
    '{"o":{"k":"v"}}',
)
acc(
    doc(e_array("nest", doc(e_array("0", doc())))),
    '{"nest":[[]]}',
)
acc(doc(e_string("", "empty-key")), '{"":"empty-key"}')

REJECT = []  # (hex, why)


def rej(b, why):
    REJECT.append((h(b), why))


REJECT.append((h(b""), "empty input"))
REJECT.append((h(b"\x04\x00\x00\x00\x00"), "length shorter than minimum"))
bad_len = doc(e_i32("a", 1))
REJECT.append((h(struct.pack("<i", 99) + bad_len[4:]), "length mismatch"))
REJECT.append((h(bad_len[:-1]), "truncated document"))
REJECT.append((h(doc(b"\x07" + cstr("o") + b"\x00" * 12)), "ObjectId policy"))
REJECT.append(
    (h(doc(b"\x09" + cstr("dt") + struct.pack("<q", 0))), "datetime policy")
)
REJECT.append(
    (
        h(doc(b"\x05" + cstr("b") + struct.pack("<i", 1) + b"\x00A")),
        "binary policy",
    )
)
REJECT.append((h(doc(b"\x13" + cstr("d") + b"\x00" * 16)), "decimal128 policy"))
REJECT.append((h(doc(e_double("nan", float("nan")))), "non-finite double"))
REJECT.append((h(doc(e_double("inf", float("inf")))), "infinite double"))
REJECT.append((h(doc(b"\x08" + cstr("b") + b"\x02")), "bool byte 0x02"))
REJECT.append((h(doc(e_i32("a", 1)) + b"\x00"), "trailing bytes"))
REJECT.append((h(doc(b"\x10" + b"noterm")), "unterminated name"))

ENCODE = []  # (json_text, expected_hex)


def enc(json_text, packed):
    ENCODE.append((json_text, h(packed)))


enc("{}", doc())
enc('{"a":1}', doc(e_i32("a", 1)))
enc('{"big":4294967296}', doc(e_i64("big", 4294967296)))
enc('{"f":1.5}', doc(e_double("f", 1.5)))
enc('{"s":"hi"}', doc(e_string("s", "hi")))
enc('{"z":null,"t":true}', doc(e_null("z"), e_bool("t", True)))
enc('{"a":[1,2]}', doc(e_array("a", doc(e_i32("0", 1), e_i32("1", 2)))))
enc('{"o":{"k":"v"}}', doc(e_doc("o", doc(e_string("k", "v")))))
enc('{"neg":-2147483648}', doc(e_i32("neg", -2147483648)))
enc('{"past":-2147483649}', doc(e_i64("past", -2147483649)))

ENCODE_REJECT = [  # (json_text, why)
    ("[1,2]", "array root"),
    ('"scalar"', "scalar root"),
    ('{"u":18446744073709551615}', "uint64 beyond Int64"),
]


def mojo_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


with open(OUT, "w") as f:
    w = f.write
    w("# GENERATED by tests/gen_bson_vectors.py — do not edit by hand.\n")
    w("# Regenerate: python3 tests/gen_bson_vectors.py && pixi run format\n")
    w("# BSON vectors: decodes compare dumps text, encodes compare exact\n")
    w(
        "# bytes, every accept round-trips encode→decode, rejects must raise.\n\n"
    )
    w("from bson import decode\n")
    w("from bson import dumps as bson_dumps\n")
    w("from json import dumps, loads\n\n\n")
    w("def _unhex(hex: String) raises -> List[UInt8]:\n")
    w("    var out = List[UInt8](capacity=hex.byte_length() // 2)\n")
    w("    var chars = hex.as_bytes()\n")
    w("    var i = 0\n")
    w("    while i + 1 < len(chars):\n")
    w("        out.append(UInt8((_nib(chars[i]) << 4) | _nib(chars[i + 1])))\n")
    w("        i += 2\n")
    w("    return out^\n\n\n")
    w("def _nib(c: UInt8) raises -> Int:\n")
    w('    if c >= UInt8(ord("0")) and c <= UInt8(ord("9")):\n')
    w('        return Int(c - UInt8(ord("0")))\n')
    w('    return Int(c - UInt8(ord("a"))) + 10\n\n\n')
    w("def _to_hex(data: List[UInt8]) -> String:\n")
    w('    comptime HEX = "0123456789abcdef"\n')
    w("    var hb = HEX.as_bytes()\n")
    w('    var out = String("")\n')
    w("    for i in range(len(data)):\n")
    w("        out += chr(Int(hb[Int((data[i] >> 4) & 15)]))\n")
    w("        out += chr(Int(hb[Int(data[i] & 15)]))\n")
    w("    return out^\n\n\n")
    w("def main() raises:\n")
    w("    var fails = 0\n")
    w("    var accepts = 0\n")
    w("    var rejects = 0\n")
    w("    var encodes = 0\n")
    w("    var roundtrips = 0\n\n")
    for hex_bytes, expected in ACCEPT:
        w("    try:\n")
        w(f"        var d = decode(_unhex({mojo_str(hex_bytes)}))\n")
        w(f"        if dumps(d) == {mojo_str(expected)}:\n")
        w("            accepts += 1\n")
        w("        else:\n")
        w(
            f"            print(\"FAIL accept:\", {mojo_str(hex_bytes)}, \"got\", dumps(d))\n"
        )
        w("            fails += 1\n")
        w("    except error:\n")
        w(
            f"        print(\"FAIL accept raised:\", {mojo_str(hex_bytes)}, String(error))\n"
        )
        w("        fails += 1\n")
    w("\n")
    for json_text, expected_hex in ENCODE:
        w("    try:\n")
        w(f"        var e = bson_dumps(loads(String({mojo_str(json_text)})))\n")
        w(f"        if _to_hex(e) == {mojo_str(expected_hex)}:\n")
        w("            encodes += 1\n")
        w("        else:\n")
        w(
            f"            print(\"FAIL encode:\", {mojo_str(json_text)}, \"got\", _to_hex(e))\n"
        )
        w("            fails += 1\n")
        w("    except error:\n")
        w(
            f"        print(\"FAIL encode raised:\", {mojo_str(json_text)}, String(error))\n"
        )
        w("        fails += 1\n")
    w("\n")
    for hex_bytes, expected in ACCEPT:
        w("    try:\n")
        w(f"        var r1 = decode(_unhex({mojo_str(hex_bytes)}))\n")
        w("        var r2 = decode(bson_dumps(r1))\n")
        w(f"        if dumps(r2) == {mojo_str(expected)}:\n")
        w("            roundtrips += 1\n")
        w("        else:\n")
        w(
            f"            print(\"FAIL roundtrip:\", {mojo_str(hex_bytes)}, \"got\", dumps(r2))\n"
        )
        w("            fails += 1\n")
        w("    except error:\n")
        w(
            f"        print(\"FAIL roundtrip raised:\", {mojo_str(hex_bytes)}, String(error))\n"
        )
        w("        fails += 1\n")
    w("\n")
    for hex_bytes, why in REJECT:
        w("    try:\n")
        w(f"        _ = decode(_unhex({mojo_str(hex_bytes)}))\n")
        w(f"        print(\"FAIL reject accepted: {why}\")\n")
        w("        fails += 1\n")
        w("    except error:\n")
        w("        rejects += 1\n")
    for json_text, why in ENCODE_REJECT:
        w("    try:\n")
        w(f"        _ = bson_dumps(loads(String({mojo_str(json_text)})))\n")
        w(f"        print(\"FAIL encode-reject accepted: {why}\")\n")
        w("        fails += 1\n")
        w("    except error:\n")
        w("        rejects += 1\n")
    w("\n")
    w('    print("bson: accepts=", accepts, " encodes=", encodes,')
    w(' " roundtrips=", roundtrips, " rejects=", rejects, " fails=", fails)\n')
    w("    if fails > 0:\n")
    w('        raise Error("BSON VECTORS FAILED")\n')
    w('    print("BSON OK")\n')

print(
    f"wrote {OUT}: {len(ACCEPT)} accept, {len(ENCODE)} encode, {len(REJECT)}+{len(ENCODE_REJECT)} reject"
)
