#!/usr/bin/env python3
# CBOR differential vectors — seeded from RFC 8949 Appendix A (the spec's
# own examples) plus policy/robustness cases, packed by hand with struct.
# Decodes compare `dumps` JSON; encodes compare exact shortest-form bytes;
# every accept round-trips encode→decode; rejects must raise.
# Regenerate: python3 tests/gen_cbor_vectors.py && pixi run format
import struct

OUT = "tests/cbor_generated.mojo"


def h(b: bytes) -> str:
    return b.hex()


def head(major, value):
    base = major << 5
    if value < 24:
        return bytes([base | value])
    if value < 256:
        return bytes([base | 24, value])
    if value < 65536:
        return bytes([base | 25]) + struct.pack(">H", value)
    if value < 4294967296:
        return bytes([base | 26]) + struct.pack(">I", value)
    return bytes([base | 27]) + struct.pack(">Q", value)


def txt(s):
    raw = s.encode()
    return head(3, len(raw)) + raw


def f16(v):
    return b"\xf9" + struct.pack(">e", v)


def f32(v):
    return b"\xfa" + struct.pack(">f", v)


def f64(v):
    return b"\xfb" + struct.pack(">d", v)


ACCEPT = []  # (hex, expected_json) — RFC 8949 Appendix A subset first


def acc(b, expected):
    ACCEPT.append((h(b), expected))


acc(head(0, 0), "0")
acc(head(0, 1), "1")
acc(head(0, 10), "10")
acc(head(0, 23), "23")
acc(head(0, 24), "24")
acc(head(0, 25), "25")
acc(head(0, 100), "100")
acc(head(0, 1000), "1000")
acc(head(0, 1000000), "1000000")
acc(head(0, 1000000000000), "1000000000000")
acc(head(0, 18446744073709551615), "18446744073709551615")
acc(head(1, 0), "-1")
acc(head(1, 9), "-10")
acc(head(1, 99), "-100")
acc(head(1, 999), "-1000")
acc(head(1, 9223372036854775807), "-9223372036854775808")
acc(b"\xf4", "false")
acc(b"\xf5", "true")
acc(b"\xf6", "null")
acc(f16(0.0), "0.0")
acc(f16(1.0), "1.0")
acc(f16(1.5), "1.5")
acc(f16(65504.0), "65504.0")
acc(f32(100000.0), "100000.0")
acc(f64(1.1), "1.1")
acc(f64(1.0e300), "1e+300")
acc(txt(""), '""')
acc(txt("a"), '"a"')
acc(txt("IETF"), '"IETF"')
acc(txt('"\\'), '"\\"\\\\"')
acc(txt("ü"), '"ü"')
acc(txt("水"), '"水"')
acc(
    txt('é"\n水'), '"é\\"\\n水"'
)  # dirty AND multibyte: raw UTF-8 survives the tail
acc(head(4, 0), "[]")
acc(head(4, 3) + head(0, 1) + head(0, 2) + head(0, 3), "[1,2,3]")
acc(
    head(4, 3)
    + head(0, 1)
    + (head(4, 2) + head(0, 2) + head(0, 3))
    + (head(4, 2) + head(0, 4) + head(0, 5)),
    "[1,[2,3],[4,5]]",
)
arr25 = head(4, 25) + b"".join(head(0, i) for i in range(1, 26))
acc(arr25, "[" + ",".join(str(i) for i in range(1, 26)) + "]")
acc(head(5, 0), "{}")
acc(
    head(5, 2)
    + txt("a")
    + head(0, 1)
    + txt("b")
    + (head(4, 2) + head(0, 2) + head(0, 3)),
    '{"a":1,"b":[2,3]}',
)
# Indefinite forms (RFC 8949 §3.2).
acc(b"\x9f" + head(0, 1) + head(0, 2) + b"\xff", "[1,2]")
acc(b"\x9f\xff", "[]")
acc(b"\xbf" + txt("k") + head(0, 7) + b"\xff", '{"k":7}')
acc(b"\x7f" + txt("strea") + txt("ming") + b"\xff", '"streaming"')
acc(b"\x9f" + (b"\x9f" + head(0, 1) + b"\xff") + b"\xff", "[[1]]")

REJECT = []


def rej(b, why):
    REJECT.append((h(b), why))


rej(b"\x40", "byte string (major 2)")
rej(b"\xc0" + txt("2013"), "tag (major 6)")
rej(b"\xf7", "undefined")
rej(b"\xf0", "simple value 16")
rej(f16(float("nan")), "NaN half")
rej(f16(float("inf")), "Infinity half")
rej(f64(float("-inf")), "-Infinity double")
rej(head(1, 18446744073709551615), "negative below Int64.MIN")
rej(bytes([0x1C]), "reserved additional info 28")
rej(b"\xff", "lone break")
rej(head(0, 1000)[:1], "truncated argument")
rej(head(4, 2) + head(0, 1), "array missing an element")
rej(head(0, 1) + head(0, 2), "trailing bytes")
rej(b"", "empty input")
rej(head(5, 1) + head(0, 1) + head(0, 2), "integer map key (policy)")
rej(b"\x7f" + b"\x9f\xff" + b"\xff", "non-text chunk in indefinite text")
rej(b"\xbf" + txt("k") + b"\xff", "break splits a map pair")
rej(b"\x9f" + head(0, 1), "unterminated indefinite array")

ENCODE = []  # (json_text, expected_hex) — shortest-form definite output


def enc(json_text, packed):
    ENCODE.append((json_text, h(packed)))


enc("0", head(0, 0))
enc("23", head(0, 23))
enc("24", head(0, 24))
enc("500", head(0, 500))
enc("1000000", head(0, 1000000))
enc("18446744073709551615", head(0, 18446744073709551615))
enc("-1", head(1, 0))
enc("-1000", head(1, 999))
enc("-9223372036854775808", head(1, 9223372036854775807))
enc("1.5", f64(1.5))
enc('"a"', txt("a"))
enc("[1,2]", head(4, 2) + head(0, 1) + head(0, 2))
enc('{"a":1}', head(5, 1) + txt("a") + head(0, 1))
enc("null", b"\xf6")
enc("true", b"\xf5")
enc("false", b"\xf4")
enc('{"nest":[[]]}', head(5, 1) + txt("nest") + (head(4, 1) + head(4, 0)))


def mojo_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


with open(OUT, "w") as f:
    w = f.write
    w("# GENERATED by tests/gen_cbor_vectors.py — do not edit by hand.\n")
    w("# Regenerate: python3 tests/gen_cbor_vectors.py && pixi run format\n")
    w("# CBOR vectors (RFC 8949 Appendix A subset + policy cases): decodes\n")
    w("# compare dumps text, encodes compare exact shortest-form bytes,\n")
    w("# accepts round-trip encode→decode, rejects must raise.\n\n")
    w("from cbor import decode\n")
    w("from cbor import dumps as cbor_dumps\n")
    w("from json import dumps, loads\n\n\n")
    w("def _unhex(hex: String) raises -> List[UInt8]:\n")
    w("    var out = List[UInt8](capacity=hex.byte_length() // 2)\n")
    w("    var chars = hex.as_bytes()\n")
    w("    var i = 0\n")
    w("    while i + 1 < len(chars):\n")
    w("        out.append(UInt8((_nib(chars[i]) << 4) | _nib(chars[i + 1])))\n")
    w("        i += 2\n")
    w("    return out^\n\n\n")
    w("def _nib(c: UInt8) raises -> Int:\n")
    w('    if c >= UInt8(ord("0")) and c <= UInt8(ord("9")):\n')
    w('        return Int(c - UInt8(ord("0")))\n')
    w('    return Int(c - UInt8(ord("a"))) + 10\n\n\n')
    w("def _to_hex(data: List[UInt8]) -> String:\n")
    w('    comptime HEX = "0123456789abcdef"\n')
    w("    var hb = HEX.as_bytes()\n")
    w('    var out = String("")\n')
    w("    for i in range(len(data)):\n")
    w("        out += chr(Int(hb[Int((data[i] >> 4) & 15)]))\n")
    w("        out += chr(Int(hb[Int(data[i] & 15)]))\n")
    w("    return out^\n\n\n")
    w("def main() raises:\n")
    w("    var fails = 0\n")
    w("    var accepts = 0\n")
    w("    var rejects = 0\n")
    w("    var encodes = 0\n")
    w("    var roundtrips = 0\n\n")
    for hex_bytes, expected in ACCEPT:
        w("    try:\n")
        w(f"        var d = decode(_unhex({mojo_str(hex_bytes)}))\n")
        w(f"        if dumps(d) == {mojo_str(expected)}:\n")
        w("            accepts += 1\n")
        w("        else:\n")
        w(
            f"            print(\"FAIL accept:\", {mojo_str(hex_bytes)}, \"got\", dumps(d))\n"
        )
        w("            fails += 1\n")
        w("    except error:\n")
        w(
            f"        print(\"FAIL accept raised:\", {mojo_str(hex_bytes)}, String(error))\n"
        )
        w("        fails += 1\n")
    w("\n")
    for json_text, expected_hex in ENCODE:
        w("    try:\n")
        w(f"        var e = cbor_dumps(loads(String({mojo_str(json_text)})))\n")
        w(f"        if _to_hex(e) == {mojo_str(expected_hex)}:\n")
        w("            encodes += 1\n")
        w("        else:\n")
        w(
            f"            print(\"FAIL encode:\", {mojo_str(json_text)}, \"got\", _to_hex(e))\n"
        )
        w("            fails += 1\n")
        w("    except error:\n")
        w(
            f"        print(\"FAIL encode raised:\", {mojo_str(json_text)}, String(error))\n"
        )
        w("        fails += 1\n")
    w("\n")
    for hex_bytes, expected in ACCEPT:
        w("    try:\n")
        w(f"        var r1 = decode(_unhex({mojo_str(hex_bytes)}))\n")
        w("        var r2 = decode(cbor_dumps(r1))\n")
        w(f"        if dumps(r2) == {mojo_str(expected)}:\n")
        w("            roundtrips += 1\n")
        w("        else:\n")
        w(
            f"            print(\"FAIL roundtrip:\", {mojo_str(hex_bytes)}, \"got\", dumps(r2))\n"
        )
        w("            fails += 1\n")
        w("    except error:\n")
        w(
            f"        print(\"FAIL roundtrip raised:\", {mojo_str(hex_bytes)}, String(error))\n"
        )
        w("        fails += 1\n")
    w("\n")
    for hex_bytes, why in REJECT:
        w("    try:\n")
        w(f"        _ = decode(_unhex({mojo_str(hex_bytes)}))\n")
        w(f"        print(\"FAIL reject accepted: {why}\")\n")
        w("        fails += 1\n")
        w("    except error:\n")
        w("        rejects += 1\n")
    w("\n")
    w('    print("cbor: accepts=", accepts, " encodes=", encodes,')
    w(' " roundtrips=", roundtrips, " rejects=", rejects, " fails=", fails)\n')
    w("    if fails > 0:\n")
    w('        raise Error("CBOR VECTORS FAILED")\n')
    w('    print("CBOR OK")\n')

print(
    f"wrote {OUT}: {len(ACCEPT)} accept, {len(ENCODE)} encode, {len(REJECT)} reject"
)
