#!/usr/bin/env python3
# Differential fuzz generator. Emits a self-contained Mojo program with:
#   - VALID canonical-compact JSON cases (no floats — dump format would diverge):
#     json-mojo must round-trip each byte-for-byte (dumps(loads(s)) == s).
#   - GARBAGE / malformed byte sequences: json-mojo must never CRASH (rejecting
#     is fine; a segfault/abort would kill the binary before the summary prints).
#
# Python's json is the oracle for canonical form. Run:
#   python3 tests/gen_fuzz.py && pixi run mojo run -I . tests/fuzz_generated.mojo
import json
import random

random.seed(20260618)  # deterministic

SAFE_CHARS = "abcXYZ012 _-.:/中café𝄞"  # incl. multibyte + solidus
ESC_CHARS = '"\\\n\t\b\f\r\x00\x01\x1f'  # force escape paths


def rand_string():
    n = random.randint(0, 12)
    pool = SAFE_CHARS + (ESC_CHARS if random.random() < 0.5 else "")
    return "".join(random.choice(pool) for _ in range(n))


def rand_int():
    # Span inline (60-bit), int64 boundary, and big-int (big_number pool).
    kind = random.random()
    if kind < 0.5:
        return random.randint(-1000, 1000)
    if kind < 0.8:
        return random.randint(-(2**62), 2**62)
    return random.randint(-(2**90), 2**90)  # exercises big_number raw text


def rand_value(depth):
    if depth <= 0:
        r = random.random()
        if r < 0.3:
            return rand_int()
        if r < 0.5:
            return rand_string()
        if r < 0.65:
            return True
        if r < 0.8:
            return False
        return None
    r = random.random()
    if r < 0.35:
        return [rand_value(depth - 1) for _ in range(random.randint(0, 6))]
    if r < 0.7:
        return {
            rand_string(): rand_value(depth - 1)
            for _ in range(random.randint(0, 6))
        }
    return rand_value(0)


def canonical(value):
    # Compact, raw-unicode — matches json-mojo's dump format for these types.
    return json.dumps(value, separators=(",", ":"), ensure_ascii=False)


def mojo_str_literal(s: str) -> str:
    # Escape for a Mojo double-quoted string literal.
    out = s.replace("\\", "\\\\").replace('"', '\\"')
    return '"' + out + '"'


def mojo_byte_list(b: bytes) -> str:
    if not b:
        return "List[UInt8]()"
    return "[" + ",".join("UInt8(%d)" % x for x in b) + "]"


# --- valid round-trip cases ------------------------------------------------
valid = []
seen = set()
while len(valid) < 400:
    v = rand_value(random.randint(0, 4))
    s = canonical(v)
    if s in seen:
        continue
    seen.add(s)
    # sanity: Python must round-trip its own canonical form
    if canonical(json.loads(s)) != s:
        continue
    valid.append(s)

# --- garbage / malformed cases (must not crash) ----------------------------
garbage = []
seeds = [canonical(rand_value(random.randint(0, 3))) for _ in range(150)]
for s in seeds:
    b = bytearray(s.encode("utf-8"))
    # random mutation
    for _ in range(random.randint(1, 4)):
        if not b:
            break
        op = random.random()
        i = random.randrange(len(b))
        if op < 0.4:
            b[i] = random.randint(0, 255)  # flip to arbitrary byte
        elif op < 0.7:
            del b[i]  # truncate
        else:
            b.insert(i, random.randint(0, 255))  # insert
    garbage.append(bytes(b))
# pure random byte soup + structural-only noise
for _ in range(150):
    n = random.randint(0, 40)
    garbage.append(bytes(random.randint(0, 255) for _ in range(n)))
for _ in range(50):
    n = random.randint(1, 60)
    garbage.append(
        "".join(random.choice('{}[],:" \t\n0-+.eE') for _ in range(n)).encode()
    )

# Data-driven emission: cases go into Lists, a single small loop checks them.
# (Inlining one block per case made `main` too large for the compiler to build.)
# Data builders are chunked into helpers to keep each function small.
CHUNK = 40
L = []
L.append("# GENERATED by tests/gen_fuzz.py — differential fuzz vs Python json.")
L.append("# Do not edit by hand; re-run the generator.")
L.append("import json")
L.append("")


def emit_chunked(name, items, render):
    fns = []
    for ci in range(0, len(items), CHUNK):
        fn = "%s_%d" % (name, ci // CHUNK)
        fns.append(fn)
        L.append("")
        L.append(
            "def %s(mut out: %s):"
            % (fn, "List[String]" if name == "_valid" else "List[List[UInt8]]")
        )
        for it in items[ci : ci + CHUNK]:
            L.append("    out.append(%s)" % render(it))
    L.append("")
    L.append(
        "def %s() -> %s:"
        % (name, "List[String]" if name == "_valid" else "List[List[UInt8]]")
    )
    L.append(
        "    var out = %s()"
        % ("List[String]" if name == "_valid" else "List[List[UInt8]]")
    )
    for fn in fns:
        L.append("    %s(out)" % fn)
    L.append("    return out^")


emit_chunked("_valid", valid, mojo_str_literal)
emit_chunked("_garbage", garbage, mojo_byte_list)

L.append("")
L.append("def main() raises:")
L.append("    var fails = 0")
L.append("    var valid = _valid()")
L.append("    for i in range(len(valid)):")
L.append("        try:")
L.append("            var got = json.dumps(json.loads(valid[i]))")
L.append("            if got != valid[i]:")
L.append('                print("RT MISMATCH in=", valid[i], " out=", got)')
L.append("                fails += 1")
L.append("        except e:")
L.append('            print("RT RAISED on valid:", valid[i], e)')
L.append("            fails += 1")
L.append("    var garbage = _garbage()")
L.append("    for i in range(len(garbage)):")
L.append("        try:")
L.append("            _ = json.loads_bytes(garbage[i].copy())")
L.append("        except:")
L.append("            pass")  # rejecting is fine; only a crash would fail
L.append(
    '    print("fuzz: roundtrip=", len(valid), " nocrash=", len(garbage), " fails=", fails)'
)
L.append("    if fails != 0:")
L.append('        raise Error("fuzz failures: " + String(fails))')
L.append('    print("FUZZ OK")')
L.append("")

with open("tests/fuzz_generated.mojo", "w") as f:
    f.write("\n".join(L))

print(
    "wrote tests/fuzz_generated.mojo: %d round-trip + %d no-crash cases"
    % (len(valid), len(garbage))
)
