#!/usr/bin/env python3
# Differential UTF-8 fuzzer. Builds JSON strings whose bodies are valid or
# INVALID UTF-8 byte sequences, and checks that json-mojo accepts/rejects each
# exactly as Python's json does (Python decodes the bytes as UTF-8 first, so it
# rejects invalid UTF-8 — the RFC 8259 §8.1 oracle).
#
#   python3 tests/gen_utf8_fuzz.py && pixi run mojo run -I . tests/utf8_generated.mojo
import json
import random

random.seed(20260618)

cases = []  # (json_bytes, expect_ok)


def add(body: bytes):
    jb = b'"' + body + b'"'
    # Oracle = STRICT RFC 3629 UTF-8 (bytes.decode), which rejects surrogates &
    # overlong forms. Note json.loads(bytes) is leniently surrogate-permissive,
    # so it is the wrong oracle here; we (and simdjson) are strict. The body is
    # generated free of quotes/backslashes/control bytes, so UTF-8 validity is
    # the only accept/reject factor.
    try:
        body.decode("utf-8")
        ok = True
    except Exception:
        ok = False
    cases.append((jb, ok))


def ascii_fill(n):
    return bytes(random.choice(b"abcXYZ 0123_-./") for _ in range(n))


# Valid: ASCII + random valid code points (incl. 2/3/4-byte, excl. surrogates).
for _ in range(200):
    parts = [ascii_fill(random.randint(0, 4))]
    for _ in range(random.randint(1, 4)):
        while True:
            cp = random.randint(0x20, 0x10FFFF)
            if 0xD800 <= cp <= 0xDFFF:
                continue
            try:
                parts.append(chr(cp).encode("utf-8"))
                break
            except Exception:
                continue
        parts.append(ascii_fill(random.randint(0, 3)))
    add(b"".join(parts))

# Invalid byte sequences embedded in ASCII.
BAD = [
    b"\x80",
    b"\xbf",
    b"\xc0\x80",
    b"\xc1\xbf",  # lone cont / overlong
    b"\xc3",
    b"\xe0\xa0",
    b"\xf0\x90\x80",  # truncated
    b"\xe0\x80\x80",
    b"\xf0\x80\x80\x80",  # overlong 3/4
    b"\xed\xa0\x80",
    b"\xed\xbf\xbf",  # surrogates U+D800/DFFF
    b"\xf4\x90\x80\x80",
    b"\xf5\x80\x80\x80",  # > U+10FFFF
    b"\xff",
    b"\xfe",
    b"\xc3\x28",
    b"\xe2\x28\xa1",  # invalid lead / bad cont
]
for seq in BAD:
    for _ in range(12):
        add(
            ascii_fill(random.randint(0, 5))
            + seq
            + ascii_fill(random.randint(0, 5))
        )

# A few pure-ASCII controls just to confirm parity on the boundary.
for _ in range(20):
    add(ascii_fill(random.randint(0, 10)))


def mojo_bytes(b: bytes) -> str:
    if not b:
        return "List[UInt8]()"
    return "[" + ",".join("UInt8(%d)" % x for x in b) + "]"


CHUNK = 40
L = [
    "# GENERATED by tests/gen_utf8_fuzz.py — differential UTF-8 test vs Python json.",
    "import json",
    "",
]


def emit(name, items, render, ty):
    fns = []
    for ci in range(0, len(items), CHUNK):
        fn = "%s_%d" % (name, ci // CHUNK)
        fns.append(fn)
        L.append("")
        L.append("def %s(mut out: %s):" % (fn, ty))
        for it in items[ci : ci + CHUNK]:
            L.append("    out.append(%s)" % render(it))
    L.append("")
    L.append("def %s() -> %s:" % (name, ty))
    L.append("    var out = %s()" % ty)
    for fn in fns:
        L.append("    %s(out)" % fn)
    L.append("    return out^")


emit("_cases", [c[0] for c in cases], mojo_bytes, "List[List[UInt8]]")
emit(
    "_oks",
    [c[1] for c in cases],
    lambda b: "True" if b else "False",
    "List[Bool]",
)

L += [
    "",
    "def main() raises:",
    "    var cs = _cases()",
    "    var oks = _oks()",
    "    var fails = 0",
    "    for i in range(len(cs)):",
    "        var got_ok = True",
    "        try:",
    "            _ = json.loads_bytes(cs[i].copy())",
    "        except:",
    "            got_ok = False",
    "        if got_ok != oks[i]:",
    '            print("UTF8 DIVERGE i=", i, " got_ok=", got_ok, " want=", oks[i])',
    "            fails += 1",
    '    print("utf8diff: cases=", len(cs), " fails=", fails)',
    "    if fails != 0:",
    '        raise Error("utf8 diff failures: " + String(fails))',
    '    print("UTF8DIFF OK")',
    "",
]

with open("tests/utf8_generated.mojo", "w") as f:
    f.write("\n".join(L))
print(
    "wrote tests/utf8_generated.mojo: %d cases (%d valid, %d invalid)"
    % (
        len(cases),
        sum(1 for c in cases if c[1]),
        sum(1 for c in cases if not c[1]),
    )
)
