#!/usr/bin/env python3
# Differential FLOAT fuzzer. Python's float() is C strtod — the correctly
# rounded oracle. For each JSON number string we emit the exact IEEE-754 bits
# Python parses; the generated Mojo program parses the same string and compares
# the bits of `to[Float64]()` BIT-FOR-BIT. Any 1-ULP error shows up.
#
#   python3 tests/gen_float_fuzz.py && pixi run mojo run -I . tests/floatdiff_generated.mojo
import json
import math
import random
import struct

random.seed(20260618)


def bits(f):
    return struct.unpack("<Q", struct.pack("<d", f))[0]


cases = []  # (json_string, expected_bits)
seen = set()


def add(s):
    if s in seen:
        return
    # Only actual FLOATS (with '.', 'e' or 'E'). Pure integers are a separate
    # JSON type — e.g. "-0" is integer 0 (+0.0), not strtod's -0.0.
    if not any(ch in s for ch in ".eE"):
        return
    try:
        if json.loads(s) is None:
            return
        f = float(s)
    except Exception:
        return
    if not math.isfinite(f):
        return
    seen.add(s)
    cases.append((s, bits(f)))


# Hand-picked: zero/neg-zero, simple decimals, exponents, the classic 0.1+0.2.
for s in [
    "0",
    "-0",
    "0.0",
    "-0.0",
    "1",
    "1.0",
    "-1",
    "3.14",
    "0.1",
    "0.2",
    "0.3",
    "2.5",
    "100.0",
    "1e0",
    "1e1",
    "1e-1",
    "1e10",
    "1e-10",
    "1.5e-2",
    "2.5E10",
    "123456789.123456789",
    "0.000001",
    "1000000.0",
    "0.30000000000000004",
    "9007199254740993",
    "1.7976931348623157e308",
    "2.2250738585072014e-308",
    "4.9e-324",
    "5e-324",
]:
    add(s)

# Known >19-digit ROUNDING-BOUNDARY cases that an approximate (round-to-19)
# fallback gets 1 ULP wrong — these MUST exercise the exact big-integer slow
# path and still match strtod. (Captured from .probe/el_prototype.py.)
for s in [
    "63542.191537960036907093330e35",
    "5.210555996198366290949163",
    "1067230664702.56189316e-12",
    "1024123097464169.187742762",
    "1519175409644649662531980.66341962001259338834399",
    "-427367901.6576133072565627762690",
    "29749414766289324033.386",
    "17101887.19903051294396445733163",
    "-94330975109136584.005749193554218969226481982128",
    "3902897.999305888902614e-28",
    "-2594960675313691227625707.4913285e-26",
]:
    add(s)

# repr() of random doubles across the whole range (shortest round-trip forms).
for _ in range(200):
    while True:
        u = random.getrandbits(64)
        f = struct.unpack("<d", struct.pack("<Q", u))[0]
        if math.isfinite(f):
            break
    add(repr(f))


# Random valid JSON number strings — stress the fast/slow path boundary with
# 1..20 significand digits and a bounded exponent.
def rand_num_str():
    sign = "-" if random.random() < 0.3 else ""
    if random.random() < 0.2:
        intp = "0"
    else:
        intp = str(random.randint(1, 9)) + "".join(
            random.choice("0123456789") for _ in range(random.randint(0, 18))
        )
    s = sign + intp
    if random.random() < 0.75:
        s += "." + "".join(
            random.choice("0123456789") for _ in range(random.randint(1, 20))
        )
    if random.random() < 0.5:
        e = random.randint(-40, 40)
        s += "e" if random.random() < 0.5 else "E"
        if e >= 0 and random.random() < 0.5:
            s += "+"
        s += str(e)
    return s


tries = 0
while len([c for c in cases]) < 1500 and tries < 60000:
    tries += 1
    add(rand_num_str())


def mojo_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


CHUNK = 40
L = [
    "# GENERATED by tests/gen_float_fuzz.py — differential float test vs Python.",
    "import json",
    "",
]


def emit(name, items, render, ty):
    fns = []
    for ci in range(0, len(items), CHUNK):
        fn = "%s_%d" % (name, ci // CHUNK)
        fns.append(fn)
        L.append("")
        L.append("def %s(mut out: %s):" % (fn, ty))
        for it in items[ci : ci + CHUNK]:
            L.append("    out.append(%s)" % render(it))
    L.append("")
    L.append("def %s() -> %s:" % (name, ty))
    L.append("    var out = %s()" % ty)
    for fn in fns:
        L.append("    %s(out)" % fn)
    L.append("    return out^")


emit("_strs", [c[0] for c in cases], lambda s: mojo_str(s), "List[String]")
emit(
    "_wantbits",
    [c[1] for c in cases],
    lambda b: "UInt64(0x%016X)" % b,
    "List[UInt64]",
)

L += [
    "",
    "def _bits_of(f: Float64) -> UInt64:",
    "    return UnsafePointer[Float64](to=f).bitcast[UInt64]()[]",
    "",
    "def main() raises:",
    "    var ss = _strs()",
    "    var wb = _wantbits()",
    "    var fails = 0",
    "    for i in range(len(ss)):",
    "        try:",
    "            var got = json.loads(ss[i]).to[Float64]()",
    "            var gb = _bits_of(got)",
    "            if gb != wb[i]:",
    '                print("FLOAT MISMATCH s=", ss[i], " got=", gb, " want=", wb[i])',
    "                fails += 1",
    "        except e:",
    '            print("FLOAT RAISED s=", ss[i], e)',
    "            fails += 1",
    '    print("floatdiff: cases=", len(ss), " fails=", fails)',
    "    if fails != 0:",
    '        raise Error("float diff failures: " + String(fails))',
    '    print("FLOATDIFF OK")',
    "",
]

with open("tests/floatdiff_generated.mojo", "w") as f:
    f.write("\n".join(L))
print("wrote tests/floatdiff_generated.mojo: %d float cases" % len(cases))
