#!/usr/bin/env python3
# ES5.1 IdentifierName character tables for Dialect.JSON5 (json5.org keys).
# IdentifierStart  = UnicodeLetter (Lu Ll Lt Lm Lo Nl) | $ | _
# IdentifierPart   = IdentifierStart | Mn | Mc | Nd | Pc | ZWNJ | ZWJ
# Ranges come from Python's unicodedata (the categories the spec names) and
# are emitted interleaved ([2k]=lo, [2k+1]=hi) into comptime InlineArrays —
# the same generated-table shape as pow5_table.mojo.
# Regenerate: python3 tests/gen_unicode_id.py && pixi run format
import sys
import unicodedata

OUT = "json/_internal/unicode_id.mojo"
CHUNK = 400  # stores per _fill function (keeps decl bodies small)

START_CATS = {"Lu", "Ll", "Lt", "Lm", "Lo", "Nl"}
CONT_EXTRA_CATS = {"Mn", "Mc", "Nd", "Pc"}


def ranges_for(predicate):
    out = []
    lo = None
    prev = None
    for cp in range(0x110000):
        if predicate(cp):
            if lo is None:
                lo = cp
            prev = cp
        else:
            if lo is not None:
                out.append((lo, prev))
                lo = None
    if lo is not None:
        out.append((lo, prev))
    return out


def is_start(cp):
    if cp in (0x24, 0x5F):  # $ _
        return True
    return unicodedata.category(chr(cp)) in START_CATS


def is_cont(cp):
    if cp in (0x200C, 0x200D):  # ZWNJ ZWJ
        return True
    c = unicodedata.category(chr(cp))
    return c in START_CATS or c in CONT_EXTRA_CATS or cp in (0x24, 0x5F)


start_ranges = ranges_for(is_start)
cont_ranges = ranges_for(is_cont)


def emit_table(w, name, ranges):
    flat = []
    for lo, hi in ranges:
        flat.append(lo)
        flat.append(hi)
    n = len(flat)
    w(f"comptime {name}_RANGES: Int = {len(ranges)}\n")
    w(f"comptime _{name}_N: Int = {n}\n\n\n")
    chunks = [flat[i : i + CHUNK] for i in range(0, n, CHUNK)]
    for ci, chunk in enumerate(chunks):
        w(
            f"def _fill_{name.lower()}_{ci}(mut t: InlineArray[UInt32, _{name}_N]):\n"
        )
        base = ci * CHUNK
        for off, v in enumerate(chunk):
            w(f"    t[{base + off}] = UInt32({v})\n")
        w("\n\n")
    w(f"def _make_{name.lower()}() -> InlineArray[UInt32, _{name}_N]:\n")
    w(f"    var t = InlineArray[UInt32, _{name}_N](uninitialized=True)\n")
    for ci in range(len(chunks)):
        w(f"    _fill_{name.lower()}_{ci}(t)\n")
    w("    return t^\n\n\n")
    w(f"comptime {name} = _make_{name.lower()}()\n\n\n")


with open(OUT, "w") as f:
    w = f.write
    w("# GENERATED by tests/gen_unicode_id.py — DO NOT EDIT.\n")
    w("# Regenerate: python3 tests/gen_unicode_id.py && pixi run format\n")
    w("#\n")
    w("# ES5.1 IdentifierName membership for Dialect.JSON5 unquoted keys —\n")
    w("# interleaved [lo, hi] code-point ranges, binary-searched; ASCII\n")
    w(
        "# answers without touching the tables. Unicode data: Python "
        f"{sys.version_info.major}.{sys.version_info.minor} unicodedata "
        f"(UCD {unicodedata.unidata_version}).\n\n\n"
    )
    emit_table(w, "ID_START", start_ranges)
    emit_table(w, "ID_CONT", cont_ranges)
    w(
        """def _in_ranges[
    n: Int
](table: InlineArray[UInt32, n], range_count: Int, cp: Int) -> Bool:
    var value = UInt32(cp)
    var lo = 0
    var hi = range_count - 1
    while lo <= hi:
        var mid = (lo + hi) // 2
        if value < table[mid * 2]:
            hi = mid - 1
        elif value > table[mid * 2 + 1]:
            lo = mid + 1
        else:
            return True
    return False


def is_id_start(cp: Int) -> Bool:
    \"\"\"ES5.1 IdentifierStart: UnicodeLetter | `$` | `_` (escape handling is
    the caller's business).\"\"\"
    if cp < 0x80:
        return (
            (cp >= 0x41 and cp <= 0x5A)
            or (cp >= 0x61 and cp <= 0x7A)
            or cp == 0x24
            or cp == 0x5F
        )
    return _in_ranges(ID_START, ID_START_RANGES, cp)


def is_id_continue(cp: Int) -> Bool:
    \"\"\"ES5.1 IdentifierPart: start characters + Mn Mc Nd Pc + ZWNJ/ZWJ.\"\"\"
    if cp < 0x80:
        return (
            (cp >= 0x41 and cp <= 0x5A)
            or (cp >= 0x61 and cp <= 0x7A)
            or (cp >= 0x30 and cp <= 0x39)
            or cp == 0x24
            or cp == 0x5F
        )
    return _in_ranges(ID_CONT, ID_CONT_RANGES, cp)
"""
    )

print(
    f"wrote {OUT}: {len(start_ranges)} start ranges, "
    f"{len(cont_ranges)} cont ranges"
)
