#!/usr/bin/env python3
# Emits json/_internal/pow5_table.mojo — the 128-bit power-of-five table for
# the Eisel-Lemire float parser, q in [-342, 308]. Verified bit-exact via
# .probe/el_prototype.py. Regenerate with: python3 tests/gen_pow5_table.py
MASK64 = (1 << 64) - 1
SMALLEST = -342
LARGEST = 308


def gen_pow5(q):
    if q >= 0:
        c = 5**q
        b = c.bit_length()
        c = c << (128 - b) if b <= 128 else c >> (b - 128)
        return c
    p = 5 ** (-q)
    b = p.bit_length()
    shift = b + 127
    c = (1 << shift) // p
    if (1 << shift) % p != 0:
        c += 1
    bb = c.bit_length()
    if bb > 128:
        c >>= bb - 128
    elif bb < 128:
        c <<= 128 - bb
    return c


vals = []
for q in range(SMALLEST, LARGEST + 1):
    v = gen_pow5(q)
    vals.append(v >> 64)
    vals.append(v & MASK64)

N = len(vals)
CHUNK = 100
L = [
    "# GENERATED by tests/gen_pow5_table.py — DO NOT EDIT.",
    "# 128-bit powers of five for the Eisel-Lemire float parser, q in [-342, 308].",
    "# POW5[2k] = high 64 bits of 5^(k-342); POW5[2k+1] = low 64 bits.",
    "# Table + algorithm verified bit-exact vs C strtod (.probe/el_prototype.py).",
    "",
    "comptime _N: Int = %d" % N,
    "",
]
fns = []
for ci in range(0, N, CHUNK):
    fn = "_fill_%d" % (ci // CHUNK)
    fns.append(fn)
    L.append("")
    L.append("def %s(mut t: InlineArray[UInt64, _N]):" % fn)
    for k in range(ci, min(ci + CHUNK, N)):
        L.append("    t[%d] = UInt64(0x%016X)" % (k, vals[k]))
L.append("")
L.append("def _make() -> InlineArray[UInt64, _N]:")
L.append("    var t = InlineArray[UInt64, _N](uninitialized=True)")
for fn in fns:
    L.append("    %s(t)" % fn)
L.append("    return t^")
L.append("")
L.append("comptime POW5 = _make()")
L.append("")

with open("json/_internal/pow5_table.mojo", "w") as f:
    f.write("\n".join(L))
print(
    "wrote json/_internal/pow5_table.mojo: %d u64 entries (q %d..%d)"
    % (N, SMALLEST, LARGEST)
)
